### PR TITLE
Updated all deps to their latest versions.

### PR DESCRIPTION
**Pull request by paymand**
This is a fix for https://github.com/appium/appium/issues/3754.
So far:
1. Appium builds fine.
2. My smoke tests pass just fine on iOS and Android (both uiautomator and Selendroid).

### CODE REVIEW

**Comment by 0x1mason** [comment]
We should get this tested before we merge.

**Comment by paymand** [comment]
@sebv: Could get some testing done with this branch please? (I'll run our smoke tests fwiw)

**Comment by paymand** [comment]
Fixed the ``morgan`` warning I mention in no 2 above.

**Comment by paymand** [comment]
I've run our smoke tests on iOS and Android (both uiautomator and Selendroid) and they pass just fine.
Now we need some feedback from the Appium tests.

**Comment by sebv** [comment]
ok to test

**Comment by paymand** [comment]
Unit tests are green :)

**Comment by 0x1mason** [comment]
Paymand, looks like there's a merge conflict.

**Comment by sebv** [comment]
just need rebase.

**Comment by paymand** [comment]
Rebased.

**Pull request merged**
