### PR TITLE
docs: address npm version as npm v7+

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Proposed changes

Recently we had a couple of issues like https://github.com/appium/appium/pull/17288 and a few reported issues related to npm version in package installation...
My understanding about main this reason was we use `peerDependencies` to resolve dependencies especially main packages in `@appium` like base driver for others.

So, I wonder we should address supported npm version as well.

I know of nodejs14 bundles npm v6, so users who use nodejs14 need to update the npm version. Others like nodejs16 bundles npm v8, so this won't be an issue for them.

what do you think...?
@mykola-mokhnach @jlipps @boneskull 
cc @saikrishna321 @SrinivasanTarget @wswebcreation

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by saikrishna321 — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
Currently package.json of appium packages contains the limitation of `node >=14, npm >= 6`, also node 14 is still being supported till spring 2023. The fact peer depencencies did not work is related to the issue package lookup issue, which might be resolved by linking `appium` to the folder where drivers are installed. 

The main different of npm7 from npm6 is that the latter forces download of peer dependencies when these are not found, which is not that we want. This unnecessary increases space usage and creates duplicates, although helps to workaround "module not found" exception while the fix above is being merged.

**Comment by mykola-mokhnach** [comment]
@boneskull to confirm

**Review by mykola-mokhnach — CHANGES_REQUESTED** [review]
see my comments above

**Comment by KazuCocoa** [comment]
Ah.. mainly space issue. I haven't deeply caught with this so I thought something dependency resolution stuff. I understand.

My concern was only in case we release potential non-workaround on user side issues like https://github.com/appium/appium/issues/17287 which prevent installing drivers, for example, to keep compatibility for npm v6 in our future work. 
(Actually, I haven't tried but the 17287 could avoid by adding peerDependency as beta.40 in the project root's peerDeps...?)

**Comment by KazuCocoa** [comment]
I succeeded in installing npm version v6 with NodeJS 16, so the 17287 actually had a workaround. https://github.com/appium/appium/issues/17287#issuecomment-1200111788 (I did not have an idea to downgrade the npm version at that time.)
Current npm version issue has workarounds to update/downgrade npm, so probably we can keep nodejs's bundled version.

Let me close this issue now.

**Pull request closed without merging**
