### PR TITLE
Removed hyphen mentioned in phone number field in gsm-call.yml file

### PR DESCRIPTION
**Pull request by navarasu**
Updated gsm-call.yml doc: Removed hyphen mention in phone number field. 

## Proposed changes
Gsm call works only with valid numbers without hyphen. So, Removed hyphen mention in phone number field in the doc.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] No code change on functionality. Minor doc file change.
## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by jlipps — APPROVED** [review]
thanks @navarasu! and @mykola-mokhnach @vrunoa: maybe we should strip out non-numeric symbols on the server side before sending over to android?

**Comment by vrunoa** [comment]
@jlipps yeah. We can do that in appium-adb before calling the gsm command.

**Review by KazuCocoa — APPROVED** [review]

**Comment by KazuCocoa** [comment]
it looks already has

```
emuMethods.gsmCall = async function (phoneNumber, action = '') {
  if (_.values(emuMethods.GSM_CALL_ACTIONS).indexOf(action) === -1) {
    throw new Error(`Invalid gsm action param ${action}. Supported values: ${_.values(emuMethods.GSM_CALL_ACTIONS)}`);
  }
  phoneNumber = `${phoneNumber}`.replace(/\s*/, "");
  if (!PHONE_NUMBER_PATTERN.test(phoneNumber)) {
    throw new Error(`Invalid gsmCall phoneNumber param ${phoneNumber}`);
  }
  await this.adbExecEmu(['gsm', action, phoneNumber]);
};
```

**Comment by imurchie** [comment]
That would just pull out spaces. `/\D*/` would do the trick.

**Pull request merged**
