### PR TITLE
let appium-chromedriver manage chromedriver completely

### LINKED ISSUE #5095: Can't npm install Appium in Appium.app because chromdwriver package requires node in path
sh: node: command not found
-[0G-[0G\[0G-[0G[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.1","npm":"2.5.1"})
[0m[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.1","npm":"2.5.1"})
[0m[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.1","npm":"2.5.1"})
[0m[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.1","npm":"2.5.1"})
[0m[37m[40mnpm[0m [0m[30m[43mWARN[0m [0m[35mengine[0m hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.1","npm":"2.5.1"})
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Darwin 14.3.0
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35margv[0m "/Users/dan/Library/Developer/Xcode/DerivedData/Appium-fgkozbnxjvnqwdezzrvawizonvbq/Build/Products/Debug/Appium.app/Contents/Resources/node/bin/node" "/Users/dan/Library/Developer/Xcode/DerivedData/Appium-fgkozbnxjvnqwdezzrvawizonvbq/Build/Products/Debug/Appium.app/Contents/Resources/node/bin/npm" "install" "appium@1.4.0"
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mnode[0m v0.12.1
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mnpm [0m v2.5.1
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m [0m[35mcode[0m ELIFECYCLE
[0m
[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m chromedriver@2.15.0 install: `node install.js`
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Exit status 127
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m 
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Failed at the chromedriver@2.15.0 install script 'node install.js'.
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m This is most likely a problem with the chromedriver package,
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m not with npm itself.
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Tell the author that this fails on your system:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     node install.js
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m You can get their info via:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     npm owner ls chromedriver
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m There is likely additional logging output above.
[0m
[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Please include the following file with any support request:
[0m[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m     /Users/dan/Library/Developer/Xcode/DerivedData/Appium-fgkozbnxjvnqwdezzrvawizonvbq/Build/Products/Debug/Appium.app/Contents/Resources/npm-debug.log
[0m2015-05-11 12:05:24.282 Appium[9462:223914] working directory doesn't exist.

### PR DESCRIPTION
**Pull request by jlipps**
fix #5095

### CODE REVIEW

**Comment by jlipps** [comment]
@Jonahss @imurchie can i get some eyes please

**Comment by jlipps** [comment]
also:

> Showing  5 changed files  with 5 additions and 99 deletions.

:+1: :-)

**Comment by Jonahss** [comment]
You know I love seeing reset.sh get smaller.
:+1:

**Comment by imurchie** [comment]
LGTM.

**Pull request merged**
