### PR TITLE
refactor: Drop @appium/docutils and @appium/typedoc-plugin-appium

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Proposed changes

We do not (cannot) maintain these modules, and they pull us back by keeping vulnerable/outdated modules. 
So lets just cut them for good.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Maybe after this, we'll keep markdown based files in https://github.com/appium/appium/blob/master/packages/appium/docs with adjusting links in the `docs` directory to follow markdown syntax on GH.
I was wondering how https://appium.io should be. I guess it will be just replaced with redirecting to the GitHub repository's docs directory (i'd like to get jlipps's knowledge/insight about documentation publishment)

**Comment by mykola-mokhnach** [comment]
I am fine with any solution which we could support (e.g. it is easy enough to understand) and have resources to maintain it.

**Comment by KazuCocoa** [comment]
yea, understood

**Comment by jlipps** [comment]
I think we should close this PR. We shouldn't remove the entire docs system, which is working just fine. Only the typedoc autogeneration.

**Pull request closed without merging**
