### PR TITLE
chore(github): replace bug report template with bug report form

### PR DESCRIPTION
**Pull request by boneskull**
This replaces the bug report template with a nice form.

I'm not sure we want to do this, but I thought I'd put it up for discussion. If we like it, we can add more forms.

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* master
  * **PR #17664** <a href="https://app.graphite.dev/github/pr/appium/appium/17664" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium/17664?utm_source=stack-comment).

**Comment by boneskull** [comment]
wish we could easily see what this looks like. hm

**Comment by boneskull** [comment]
It looks like this.  I'll need to fix the "environment" textarea

image

**Review by KazuCocoa — APPROVED** [review]

**Review by jlipps — APPROVED** [review]
cool! does this feature allow the user to select bug report or not? i.e., if they have a feature suggestion they don't have to use this form, correct?

**Comment by boneskull** [comment]
@jlipps 

When someone clicks "new issue", they see:

image

**Comment by boneskull** [comment]
...and **Feature Request** sends them off to the feature template (which we could also replace w/ a form).

**Pull request merged**
