### PR TITLE
implemented all patches into appium code

### PR DESCRIPTION
**Pull request by vavadikb**
Changes made:
- implemented all patches into 1 appium repo

### CODE REVIEW

**Comment by gooroo-ai** [comment]
@gooroodev review

**Comment by oleksandr-vonahi** [comment]
@gooroodev can you review the changes?

**Comment by gooroodev** [comment]
Thanks, @oleksandr-vonahi, for the ping!

| Mistakes | Typos | Security | Performance | Best Practices | Readability | Others |
|----------|-------|----------|-------------|----------------|-------------|--------|
| 0        | 1     | 2        | 2           | 4              | 3           | 1      |

### Summary of Changes
The pull request introduces several new functionalities and error-handling mechanisms into the Appium codebase. These include:
1. New methods to check the status of WebDriverAgent (WDA) and ADB connections.
2. Enhanced error handling for specific error messages, including custom exit codes.
3. Custom logic for verifying and managing local static paths for applications.
4. New utility functions for shell command execution and URL parsing.
5. Additional logging for better traceability.

### Found Issues

| ID  | Type         | Details                                                                                                                                                           | Severity   | Confidence |
|-----|--------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|------------|
| 1   | Typos        | "downloadIsNeaded" should be "downloadIsNeeded" in multiple places.                                                                                               | 🟡 Low     | 🔴 High    |
| 2   | Security     | Directly using `process.exit()` can lead to ungraceful shutdowns. Consider using a more controlled shutdown mechanism.                                           | 🟠 Medium  | 🔴 High    |
| 3   | Security     | Shell command injection risk in `executeShell` and `executeShellWPromise` functions. Validate or sanitize input commands.                                         | 🟠 Medium  | 🔴 High    |
| 4   | Performance  | Multiple calls to `fs.exists` in a loop can be optimized by caching the result.                                                                                   | 🟠 Medium  | 🟠 Medium  |
| 5   | Performance  | Repeatedly opening and closing files in loops can be optimized. Consider using a more efficient file handling approach.                                           | 🟠 Medium  | 🟠 Medium  |
| 6   | Best Practices | Use of `console.log` for logging. Replace with a proper logging mechanism.                                                                                        | 🟠 Medium  | 🟠 Medium  |
| 7   | Best Practices | Hardcoding error messages and exit codes. Consider using constants or enums for better maintainability.                                                           | 🟠 Medium  | 🟠 Medium  |
| 8   | Best Practices | The use of `@ts-ignore` should be minimized and properly documented if necessary.                                                                                 | 🟠 Medium  | 🟠 Medium  |
| 9   | Readability  | Long functions with nested try-catch blocks can be refactored for better readability and maintainability.                                                          | 🟠 Medium  | 🟠 Medium  |
| 10  | Readability  | Inline comments explaining patches should be removed or converted into proper documentation.                                                                      | 🟠 Medium  | 🟠 Medium  |
| 11  | Others       | Missing newline at the end of the new file `mcloud-utils.ts`.                                                                                                      | 🟡 Low     | 🔴 High    |

### Code Snippets for Fixes

1. **Typos:**
   ```javascript
   // Replace "downloadIsNeaded" with "downloadIsNeeded" in all occurrences
   let downloadIsNeeded = true;
   ```

2. **Security:**
   ```javascript
   // Replace process.exit() with a controlled shutdown mechanism
   process.exitCode = exitCode;
   setTimeout(() => process.exit(), 1000); // Allow time for cleanup
   ```

3. **Security:**
   ```javascript
   // Validate or sanitize input commands in executeShell and executeShellWPromise
   function sanitizeCommand(command) {
     // Implement command sanitization logic here
     return command;
   }

   async function executeShellWPromise(shellCommand) {
     const execPromisify = util.promisify(exec);
     return await execPromisify(sanitizeCommand(shellCommand));
   }
   ```

4. **Performance:**
   ```javascript
   // Cache the result of fs.exists to avoid multiple calls in a loop
   let localFileExists = await fs.exists(localFile);
   if (localFileExists) {
     // Use localFileExists instead of calling fs.exists again
   }
   ```

5. **Performance:**
   ```javascript
   // Optimize file handling by reducing open/close operations
   const lockFileHandle = await fs.open(lockFile, 'w');
   // Perform operations
   await lockFileHandle.close();
   ```

6. **Best Practices:**
   ```javascript
   // Replace console.log with proper logging
   logger.info(`Cannot find any free port in range. Error message: ${err.message} Appium exit with code 1`);
   ```

7. **Best Practices:**
   ```javascript
   // Use constants for error messages and exit codes
   const ERR_CANNOT_FIND_PORT = "Cannot find any free port in range";
   if (err.message.toLowerCase().includes(ERR_CANNOT_FIND_PORT.toLowerCase())) {
     logger.error(`${ERR_CANNOT_FIND_PORT}. Error message: ${err.message} Appium exit with code 1`);
     process.exit(1);
   }
   ```

8. **Best Practices:**
   ```javascript
   // Minimize the use of @ts-ignore and document if necessary
   // @ts-ignore: Explain why this is ignored
   await fs.close(await fs.open(lockFile, 'w'));
   ```

9. **Readability:**
   ```javascript
   // Refactor long functions with nested try-catch blocks
   async function handleFileOperations() {
     try {
       // File operations
     } catch (error) {
       // Handle error
     }
   }

   // Call the function
   handleFileOperations();
   ```

10. **Readability:**
    ```javascript
    // Convert inline comments to proper documentation
    /**
     * Custom logic for verification of local static path for APPs.
     * Checks the actuality of the local application file and updates if necessary.
     */
    ```

11. **Others:**
    ```javascript
    // Add newline at the end of the file
    export {
      getLocalAppsFolder,
      getSharedFolderForAppUrl,
      getLocalFileForAppUrl,
      getFileContentLength,
      executeShell,
      executeShellWPromise,
      parseWDAUrl,
      getWDAStatus
    }
    ```

### General Review of Code Quality and Style
The code introduces several new functionalities and error-handling mechanisms that enhance the robustness of the Appium codebase. However, there are areas where improvements can be made, particularly in terms of security, performance, and readability. The use of constants for error messages and exit codes, proper logging mechanisms, and minimizing the use of `@ts-ignore` are recommended best practices. Additionally, refactoring long functions and nested try-catch blocks can improve readability and maintainability. Overall, the code changes are valuable but require some refinements to adhere to best practices and ensure optimal performance and security.

--
I **only** arrive when I am mentioned and asked to review the pull request.
Please add a reaction or reply to let me know your feedback.

**Comment by gooroodev** [comment]
Thanks, @oleksandr-vonahi! Ready to assist!

| Mistakes | Typos | Security | Performance | Best Practices | Readability | Others |
|----------|-------|----------|-------------|----------------|-------------|--------|
| 1        | 1     | 2        | 2           | 3              | 2           | 1      |

### Summary of Changes
1. Added new utility functions to handle device status checks and file operations.
2. Introduced custom logic to manage local application files and their integrity.
3. Added new routes for checking the status of WDA and ADB.
4. Enhanced error handling with specific exit codes based on error messages.
5. Updated caching and file handling mechanisms to improve local application file management.

### Found Issues
| ID | Type          | Details                                                                                                 | Severity     | Confidence |
|----|---------------|---------------------------------------------------------------------------------------------------------|--------------|------------|
| 1  | Best Practices| Use of `process.exit` in multiple places without proper cleanup or logging.                             | 🔴 High      | High       |
| 2  | Security      | Potential command injection via shell commands in `executeShellWPromise`.                               | 🔴 High      | High       |
| 3  | Performance   | Repeatedly checking for file existence in a loop without a delay.                                        | 🟠 Medium    | High       |
| 4  | Readability   | Inconsistent use of single and double quotes.                                                            | 🟡 Low       | High       |
| 5  | Best Practices| Missing error handling in async functions.                                                              | 🔴 High      | High       |
| 6  | Performance   | Using synchronous file operations in `process.on('exit')` handler.                                      | 🟠 Medium    | High       |
| 7  | Mistakes      | Incorrect import statement in `getSharedFolderForAppUrl` function.                                       | 🔴 High      | High       |
| 8  | Readability   | Inconsistent logging messages, making it hard to trace.                                                  | 🟡 Low       | High       |
| 9  | Security      | Hardcoded sensitive information like `sessionId` and `deviceId`.                                        | 🔴 High      | High       |
| 10 | Others        | Use of `@ts-nocheck` without justification.                                                             | 🟡 Low       | High       |
| 11 | Typos         | Typo in variable name `downloadIsNeaded` should be `downloadIsNeeded`.                                   | 🟡 Low       | High       |

### Fixes

#### 1. Use of `process.exit` in multiple places without proper cleanup or logging
```javascript
// Example fix in core.ts
async getStatusWDA(exitCode?: number | null) {
  // ... existing code ...
  if (exitCode != null) {
    this.log.error("Error for sending of WDA status http call. See appium logs for details")
    this.log.warn(`[MCLOUD] Killing Appium instance with "exit(${exitCode})"`);
    await cleanUpResources(); // Custom cleanup function
    process.exit(exitCode);
  }
  // ... existing code ...
}

// Define a cleanup function
async function cleanUpResources() {
  // Perform necessary cleanup operations
  logger.info("Cleaning up resources before exiting...");
}
```

#### 2. Potential command injection via shell commands in `executeShellWPromise`
```javascript
// Example fix in mcloud-utils.ts
async function executeShellWPromise(shellCommand) {
  const execPromisify = util.promisify(exec);
  if (typeof shellCommand !== 'string') {
    throw new Error('Invalid shell command');
  }
  return await execPromisify(shellCommand);
}
```

#### 3. Repeatedly checking for file existence in a loop without a delay
```javascript
// Example fix in helpers.js
while(!await fs.exists(localFile) && (attemptsCount++ < maxAttemptsCount)) {
  await new Promise((resolve) => {
    logger.info(`[MCLOUD] Attempt #${attemptsCount} for local app file to appear again`);
    setTimeout(resolve, waitingTime);
  });
}
```

#### 4. Inconsistent use of single and double quotes
```javascript
// Example fix in helpers.js
logger.info('[MCLOUD] Local version of app was found. Will check actuality of the file');
```

#### 5. Missing error handling in async functions
```javascript
// Example fix in mcloud-utils.ts
async function getLocalAppsFolder() {
  try {
    if (process.env.APPIUM_APPS_DIR === undefined || process.env.APPIUM_APPS_DIR === '') {
      return undefined;
    } else {
      return process.env.APPIUM_APPS_DIR;
    }
  } catch (error) {
    logger.error('Error getting local apps folder:', error);
    throw error;
  }
}
```

#### 6. Using synchronous file operations in `process.on('exit')` handler
```javascript
// Example fix in helpers.js
process.on('exit', async () => {
  for (const appPath of appPaths) {
    try {
      logger.info(`[MCLOUD] process.on('exit'). Deleting files by path: ${appPath}`);
      await fs.rimraf(appPath);
    } catch (e) {
      logger.warn(e.message);
    }
  }
});
```

#### 7. Incorrect import statement in `getSharedFolderForAppUrl` function
```javascript
// Example fix in mcloud-utils.ts
await fs.mkdir(targetPath, {recursive : true});
```

#### 8. Inconsistent logging messages
```javascript
// Example fix in helpers.js
logger.info(`[MCLOUD] Attempt #${attemptsCount} for local app file to appear again`);
```

#### 9. Hardcoded sensitive information like `sessionId` and `deviceId`
```javascript
// Example fix in helpers.js
var sessionId = process.env.sessionId || 'unknown session ID';
var deviceId = process.env.DEVICE_UDID || 'unknown device UUID';
```

#### 10. Use of `@ts-nocheck` without justification
```javascript
// Example fix in plugin.js
// Add a comment explaining why @ts-nocheck is necessary
// @ts-nocheck: This file uses dynamic imports which TypeScript cannot type check
```

#### 11. Typo in variable name `downloadIsNeaded` should be `downloadIsNeeded`
```javascript
// Example fix in helpers.js
let downloadIsNeeded = true;
```

### General Review
The incoming changes introduce several useful functionalities and enhancements but also bring some issues that need addressing. The code quality is generally good, but there are areas where improvements can be made, particularly in error handling, security, and performance. Consistency in logging and coding style should be maintained for better readability and maintainability.

--
I **only** arrive when I am mentioned and asked to review the pull request.
React or reply to keep the discussion going!

**Pull request closed without merging**
