### PR TITLE
Fix #6044

### LINKED ISSUE #6044: Error: Could not get the Java version. Is Java installed?
```
$ appium
info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.womistudios.arcadetap.aphone","appActivity":"com.womistudios.arcadetap.aphone.Splashscreen","platformName":"Android","udid":"10.0.0.9","deviceName":"S8WCV8UWGUJ7MVNF"}}
info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_45-internal)
info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
info: [debug] Creating new appium session e0bf11a2-06b5-49d9-8790-75c04768efc0
info: Starting android appium
info: [debug] Getting Java version
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not get the Java version. Is Java installed?
info: [debug] Error: Could not get the Java version. Is Java installed?
    at [object Object].<anonymous> (/home/perk/node-v4.2.1-linux-x64/lib/node_modules/appium/lib/devices/android/android-common.js:1062:17)
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not get the Java version. Is Java installed?)","origValue":"Could not get the Java version. Is Java installed?"},"sessionId":null}
info: <-- POST /wd/hub/session 500 91.143 ms - 222
```

```
$ java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
```
$ java -version
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode) 
```

### PR DESCRIPTION
**Pull request by MiteshShah**
```
$ appium
info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.whostudios.arcadetap.aphone","appActivity":"com.whostudios.arcadetap.aphone.Splashscreen","platformName":"Android","deviceName":"S8WCV8UWGUJ7MVNF"}}
info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_45-internal)
info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
info: [debug] Creating new appium session 9ea8ac1f-60e7-4f8e-9f9e-589058a3b82d
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.8.0_45-internal
info: [debug] Checking whether adb is present
info: [debug] Using adb from /home/mitesh/Android/Sdk/platform-tools/adb
warn: No app capability, can't parse package/activity
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's already on the device
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb devices
info: [debug] 1 device(s) connected
info: Found device S8WCV8UWGUJ7MVNF
info: [debug] Setting device id to S8WCV8UWGUJ7MVNF
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF wait-for-device
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Getting device API level
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 21
info: Device API level is: 21
info: [debug] Extracting strings for language: default
info: [debug] Apk doesn't exist locally
info: [debug] Could not get strings, but it looks like we had an old strings file anyway, so ignoring
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF shell "rm -rf /data/local/tmp/strings.json"
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Skipping install since we launched with a package instead of an app path
info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF forward tcp:4724 tcp:4724
info: [debug] Pushing appium bootstrap to device...
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF push "/home/mitesh/node-v4.2.1-linux-x64/lib/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
info: [debug] Pushing settings apk to device...
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF install "/home/mitesh/node-v4.2.1-linux-x64/lib/node_modules/appium/build/settings_apk/settings_apk-debug.apk"
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF install "/home/mitesh/node-v4.2.1-linux-x64/lib/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.whostudios.arcadetap.aphone -e disableAndroidWatchers false
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF shell "dumpsys window"
info: [debug] Screen already unlocked, continuing.
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\/local\/tmp"}
info: [debug] dataDir set to: /data/local/tmp
info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
info: [debug] Getting device API level
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 21
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.whostudios.arcadetap.aphone/com.whostudios.arcadetap.aphone.Splashscreen"
info: [debug] Waiting for pkg "com.whostudios.arcadetap.aphone" and activity "com.whostudios.arcadetap.aphone.Splashscreen" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF shell "dumpsys window windows"
info: [debug] executing cmd: /home/mitesh/Android/Sdk/platform-tools/adb -s S8WCV8UWGUJ7MVNF shell "getprop ro.build.version.release"
info: [debug] Device is at release version 5.0
info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to the default of 60 secs
info: [debug] Appium session started with sessionId 9ea8ac1f-60e7-4f8e-9f9e-589058a3b82d
info: <-- POST /wd/hub/session 303 8841.373 ms - 74 
info: --> GET /wd/hub/session/9ea8ac1f-60e7-4f8e-9f9e-589058a3b82d {}
info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"5.0","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appPackage":"com.whostudios.arcadetap.aphone","appActivity":"com.whostudios.arcadetap.aphone.Splashscreen","platformName":"Android","deviceName":"S8WCV8UWGUJ7MVNF"},"appPackage":"com.whostudios.arcadetap.aphone","appActivity":"com.whostudios.arcadetap.aphone.Splashscreen","platformName":"Android","deviceName":"S8WCV8UWGUJ7MVNF"},"sessionId":"9ea8ac1f-60e7-4f8e-9f9e-589058a3b82d"}
info: <-- GET /wd/hub/session/9ea8ac1f-60e7-4f8e-9f9e-589058a3b82d 200 9.743 ms - 661 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"5.0","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appPackage":"com.whostudios.arcadetap.aphone","appActivity":"com.whostudios.arcadetap.aphone.Splashscreen","platformName":"Android","deviceName":"S8WCV8UWGUJ7MVNF"},"appPackage":"com.whostudios.arcadetap.aphone","appActivity":"com.whostudios.arcadetap.aphone.Splashscreen","platformName":"Android","deviceName":"S8WCV8UWGUJ7MVNF"},"sessionId":"9ea8ac1f-60e7-4f8e-9f9e-589058a3b82d"}
```

### CODE REVIEW

**Comment by moizjv** [comment]
Can one of the admins verify this patch?

**Comment by MiteshShah** [comment]
@moizjv We are using openjdk so with above modification Appium runs like charm :)

**Comment by moizjv** [comment]
@MiteshShah i dont know what did you change; we are already checking for openjdk version  `new RegExp("java version|openjdk version"`

**Comment by MiteshShah** [comment]
@moizjv I'm not sure how did you check but while using openjdk we face #6044 
Above fix help me to fix #6044

**Comment by Jonahss** [comment]
@MiteshShah Your change really shouldn't make a difference. Could you try checking out the current master of Appium and running with that? (Without your PR). I'm thinking that it will work :)

**Comment by moizjv** [comment]
@MiteshShah thanks for taking time and fixing it :) you are right it does not work with 1.4 as we forgot to cherry pick it from master to 1.4; if you run from latest master it should still work. Can you test it with 1.5-beta it should work fine. Thanks !

**Pull request closed without merging**
