### PR TITLE
only allow cors when using a special flag

### PR DESCRIPTION
**Pull request by jlipps**
depends on https://github.com/appium/appium-base-driver/pull/285

### CODE REVIEW

**Review by dpgraham — APPROVED** [review]

**Comment by dpgraham** [comment]
Can you also update: https://github.com/appium/appium/blob/e4f5722ab2421108b84e7f310e30636c441386d8/docs/en/writing-running-appium/server-args.md

**Review by KazuCocoa — COMMENTED** [review]
👀

**Comment by jlipps** [comment]
good idea, @dpgraham. added.

**Review by dpgraham — APPROVED** [review]

**Comment by jlipps** [comment]
i guess we should note this in the changelog as a breaking change

**Comment by dpgraham** [comment]
Added it to changelog

**Pull request merged**
