### PR TITLE
set Executable and Registered on bundle instead of root

### PR DESCRIPTION
**Pull request by theyelllowdart**
fixes locationd[50056]: type IDs do not match - 7 vs 18 error
reverts bundle scope logic to pre 03ae1ab

### CODE REVIEW

**Comment by theyelllowdart** [comment]
fyi, I also experimented with completely omitting Executable and Registered which worked on a 8.4 simulator. Are the Executable and Registered keys required for older iOS versions?

**Comment by jlipps** [comment]
@Jonahss should have a look at this. it's possible both ways will be broken for certain xcodes and certain ios versions. we might need to keep both versions of the code around depending. and it should be in the new ios-sim package. thanks for looking into this!

**Comment by Jonahss** [comment]
Should I be looking into this? I think @imurchie should since they're now working directly with this.

**Comment by jlipps** [comment]
sure, whoever's working on it now

**Comment by imurchie** [comment]
I'll take a look.

**Comment by imurchie** [comment]
Unfortunately, in the shuffle of Appium 1.5, this PR got very messed up. If the problem that it was meant to solve persists in 1.5, can you either (a) open an issue explaining the problem and the solution, or (b) open a new PR?

We apologize for the mess up. :(

**Pull request closed without merging**
