### PR TITLE
add notice about our CLA

### PR DESCRIPTION
**Pull request by jlipps**
we should have a CLA. looking for a +1 from @bootstraponline @penguinho @imurchie @Jonahss @moizjv @scottdixon

### CODE REVIEW

**Comment by scottdixon** [comment]
+1

**Comment by Jonahss** [comment]
+1

**Comment by bootstraponline** [comment]
:+1:

**Comment by imurchie** [comment]
:+1:

**Comment by jlipps** [comment]
ok merged! let's make sure to start asking people to sign this when they do PRs, and retroactively find committers and have them sign it as well.

**Pull request merged**
