### PR TITLE
fix(base-driver): use new mixin strategy

### PR DESCRIPTION
**Pull request by boneskull**
This applies the same kind of changes made to `FakeDriver` to `BaseDriver`.  Unlike `FakeDriver`, we
already have the interfaces defined in `@appium/types`, so we can reuse them.

Note that `BaseDriverCore` is no longer a thing; the class is just called `BaseDriver`. Hopefully
this will be less confusing.

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* master
  * **PR #18261** <a href="https://app.graphite.dev/github/pr/appium/appium/18261" target="_blank">Graphite</a> 
    * **PR #18265** <a href="https://app.graphite.dev/github/pr/appium/appium/18265" target="_blank">Graphite</a> 
      * **PR #18266** <a href="https://app.graphite.dev/github/pr/appium/appium/18266" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium/18266?utm_source=stack-comment).

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* master
  * **PR #18261** <a href="https://app.graphite.dev/github/pr/appium/appium/18261" target="_blank">Graphite</a> 
    * **PR #18265** <a href="https://app.graphite.dev/github/pr/appium/appium/18265" target="_blank">Graphite</a> 
      * **PR #18266** <a href="https://app.graphite.dev/github/pr/appium/appium/18266" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium/18266?utm_source=stack-comment).

**Review by jlipps — APPROVED** [review]
i didn't read any implementation code since I figured it was just ported without change. the mixin stuff looks good. 👍 to no more BaseDriverCore!

**Comment by boneskull** [comment]
yes, I don't think I changed any implementation code other than "stuff to make the compiler shut up".  stuff like `parseInt(x, 10)` should really be `parseInt(String(x), 10)` (because `parseInt` doesn't expect a `number`, apparently?)

**Pull request merged**
