### PR TITLE
Add documentation on mobile: alert script

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Please merge it after https://github.com/appium/appium-xcuitest-driver/pull/430

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by mykola-mokhnach** [comment]
@KazuCocoa FYI

**Review by jlipps — APPROVED** [review]

**Review by KazuCocoa — APPROVED** [review]
👍

**Pull request merged**
