### PR TITLE
automationName capability values specific to iOS & Android are updated

### PR DESCRIPTION
**Pull request by vikramvi**
## Proposed changes

automationName capability values specific to Android, iOS are update. 
This will help new users of Appium

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by vikramvi** [comment]
@jlipps @imurchie can you please review

**Review by jlipps — COMMENTED** [review]
Good idea. I think we should spell it `UiAutomator2`. There are also some other automationNames we should add to the list, like: `YouiEngine` and `Espresso`

**Comment by vikramvi** [comment]
@jlipps please review latest changes, if all is ok; I can squash commits before merging into master

**Review by imurchie — APPROVED** [review]

**Comment by vikramvi** [comment]
squash task is completed, please merge this PR as it's already approved @jlipps  @imurchie

**Pull request merged**
