### PR TITLE
Add appium-doctor and update bins

### PR DESCRIPTION
**Pull request by imurchie**
Use the packages themselves.

### CODE REVIEW

**Comment by jlipps** [comment]
hmm, earlier I intentionally removed appium-doctor as a dependency because it depends on socket.io or some such that has problems compiling on all platforms. i also updated the docs to have instructions on how to use appium-doctor that don't involve installing it with appium. if we want to bring appium-doctor back in i think we need to resolve the issue with the npm+node versions that were not able to install socket.io on a first go

**Comment by imurchie** [comment]
Ah. Didn't know that. If you can remember the details, can you create an issue in `appium-doctor`?

**Comment by imurchie** [comment]
Opened PR to remove: https://github.com/appium/appium/pull/5979

**Comment by jlipps** [comment]
shoot i don't remember now but I remember @scottdixon originally brought it up, so maybe he remembers?

**Comment by scottdixon** [comment]
@imurchie https://github.com/appium/appium-doctor/issues/10

**Pull request merged**
