### PR TITLE
chore: Remove deprecated 'ANDROID_SDK_ROOT` 

### PR DESCRIPTION
**Pull request by Dor-bl**
## Proposed changes

According to https://developer.android.com/tools/variables 'ANDROID_SDK_ROOT`  is deprecated, so no point in showing this Var in the error message for the users.
image

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the CLA
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Dor-bl** [comment]
@mykola-mokhnach, I should update https://github.com/appium/appium-adb/blob/master/lib/helpers.js#L66C1-L68 as well?

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach, I should update https://github.com/appium/appium-adb/blob/master/lib/helpers.js#L66C1-L68 as well?

No need. It does not hurt to keep it

**Comment by Dor-bl** [comment]
> > @mykola-mokhnach, I should update https://github.com/appium/appium-adb/blob/master/lib/helpers.js#L66C1-L68 as well?
> 
> No need. It does not hurt to keep it

 I thought it was related to the fact why the e2e test failed.

**Comment by mykola-mokhnach** [comment]
> > > @mykola-mokhnach, I should update https://github.com/appium/appium-adb/blob/master/lib/helpers.js#L66C1-L68 as well?
> > 
> > 
> > No need. It does not hurt to keep it
> 
> I thought it was related to the fact why the e2e test failed.

It could be, but removing it would be a breaking change, and I am not very happy about breaking things for working client scripts, especially just because of a single environment variable. It is ok to remove the mention of it from docs though.

**Comment by Dor-bl** [comment]
@mykola-mokhnach , After I returned the [delete process.env.ANDROID_SDK_ROOT](https://github.com/appium/appium/blob/35356709a21dae35a491752c82997072c6aacb2b/packages/doctor/test/unit/android.spec.js#L91) in `android.spec.js` the Appium build is passing

**Review by mykola-mokhnach — APPROVED** [review]

**Pull request merged**
