### PR TITLE
XCUITest now supports swipe gestures

### PR DESCRIPTION
**Pull request by BasThomas**
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Review by jlipps — APPROVED** [review]

**Comment by vikramvi** [comment]
@BasThomas adding few sample test cases can be helpful to community, as I see many issues/queries related to swipe

**Comment by BasThomas** [comment]
Sure - where do you suggest to add these, @vikramvi?

**Comment by SrinivasanTarget** [comment]
@vikramvi XCUITest is only for iOS 9.3+ not for android. @BasThomas If you would like to add sample tests please add it here: https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/XCUIAutomationTest.java

**Comment by BasThomas** [comment]
Is there a reason to only add a test to the Java Client, as what I gather is what both of you are suggesting?

**Comment by BasThomas** [comment]
Also, are test cases that important for the community? Yes, I'd love to add test cases, but isn't it examples that can help the community? What is the issue we are facing exactly?

**Comment by vikramvi** [comment]
@BasThomas  Looking at the issues filed in github repo and queries asked in appium forum, many users are not clear how to automate basic gestures.

Referring to existing examples helps to understand and learn quickly.

This is just a suggestion for better knowledge sharing with majority

**Pull request merged**
