### PR TITLE
chore(appium): remove ios-webkit-debug-proxy-launcher; closes #16486

### LINKED ISSUE #16486: remove ios-webkit-debug-proxy-launcher
Per @KazuCocoa:

> i think it can be dropped completely. It was for some legacy iOS webview stf probably before remote-debugger, or appium-ios-driver that is already in Aappium-boneyard 

This file is in `packages/appium/bin`.

### PR DESCRIPTION
**Pull request by boneskull**
... that's about it. Also removed `bin` from the published `appium` package, since it's now empty.

closes #16486

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]
lgtm

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
I assume we also need to update the documentation where this tool is mentioned

**Comment by boneskull** [comment]
OK, sounds like @KazuCocoa will take care of removing from docs (I'm seeing 14 files mentioning this tool)

**Comment by boneskull** [comment]
Before this gets merged, @KazuCocoa wanted @mykola-mokhnach and/or @jlipps to confirm it can safely be removed?

**Comment by KazuCocoa** [comment]
jlips also addressed this command was no longer used in slack, so I think we can merge this 🚀

**Comment by mykola-mokhnach** [comment]
It can be safely removed, I've already approved the PR

**Review by jlipps — COMMENTED** [review]
yep 👍

**Pull request merged**
