### PR TITLE
Fix for #3942: Removed fruitstrap (use node-idevice everywhere).

### PR DESCRIPTION
**Pull request by paymand**
Fix for #3942. Let's get rid of `fruitstrap` for good.
I've tested it on device with both .ipa and .app and it works fine.
Also added a pr to allow for spaces in app path here: https://github.com/OniOni/node-idevice/pull/4

### CODE REVIEW

**Comment by paymand** [comment]
All usages of ``fruitstrap`` should be replaced by ``ideviceinstaller`` except for the mentions in English and Chinese docs. I'll leave it to someone else to fix.

**Comment by jlipps** [comment]
@Jonahss please review, this intersects with work you're doing I think

**Comment by jlipps** [comment]
@0x1mason should we add this and #3942 to 1.4?

**Comment by paymand** [comment]
Lots of open issues regarding ``fruitstrap`` which hopefully be addressed:
https://github.com/appium/appium/search?q=fruitstrap&state=open&type=Issues&utf8=✓

**Comment by 0x1mason** [comment]
@jlipps Def. 

Good stuff, @paymand.

**Comment by sjrjanardhana** [comment]
i am getting Could not initialise ideviceinstaller; make sure it is installed  and works on your system

is ideviceinstaller is not part of the Appium.app ?

I have installed latest Appium 1.3.6 and started seeing this issue.

Here is the server logs.

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: <-- GET /wd/hub/status 200 8.344 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: <-- GET /wd/hub/status 200 4.385 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: <-- GET /wd/hub/status 200 1.669 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: --> GET /wd/hub/sessions {}

info: [debug] Responding to client with success: {"status":0,"value":[]}

info: <-- GET /wd/hub/sessions 200 1.344 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.2","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone"}}

info: Client User-Agent string: Appium (unknown version) CFNetwork/673.3 Darwin/13.4.0 (x86_64) (MacBookPro10%2C1)

info: [debug] App is an iOS bundle, will attempt to run as pre-existing
info: [debug] Creating new appium session 82a46d2c-38ac-4519-9a14-f9cef9a12bad
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 8.2

info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate

info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/com.dishnetwork.DANY-Mobile/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/com.dishnetwork.DANY-Mobile/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/slinger/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium_1.3.6.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/slinger/Library/Application Support/appium/bootstrap/bootstrap-e8bc672756e7f571.js
info: [debug] Reusing dynamic bootstrap: /Users/slinger/Library/Application Support/appium/bootstrap/bootstrap-e8bc672756e7f571.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPhone","platformVersion":"8.2"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone (8.2 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons

info: [debug] On a real device; cannot clean device state
info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole

info: [debug] Not pre-launching simulator

info: [debug] Creating iDevice object with udid 36aa9e8432c4c702a9695235bf252531aaf8a01e

error: Could not initialize ideviceinstaller; make sure it is installed and works on your system

info: [debug] Couldn't find ideviceinstaller, trying built-in at /Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/build/libimobiledevice-macosx/ideviceinstaller
info: [debug] Cleaning up appium session
info: [debug] Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
    at IOS.getIDeviceObj (/Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:906:13)
    at IOS.installToRealDevice (/Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:853:32)
    at /Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:610:21
    at /Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:249:17
    at iterate (/Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:149:13)
    at /Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:160:25
    at /Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:251:21
    at /Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:615:34
    at IOS.prelaunchSimulator (/Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1189:12)
    at /Applications/Appium_1.3.6.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:610:21
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not initialize ideviceinstaller; make sure it is installed and works on your system)","origValue":"Could not initialize ideviceinstaller; make sure it is installed and works on your system"},"sessionId":null}

error: Failed to start an Appium session, err was: Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system

info: <-- POST /wd/hub/session 500 1314.246 ms - 300 

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: <-- GET /wd/hub/status 200 3.257 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

**Comment by paymand** [comment]
Appium comes with *some* version of ``ideviceinstaller``, but I doubt it's the latest.
Anyway, if you have homebrew on your machine, you can install it by running ``brew install ideviceinstaller``. I have version 1.1.0 installed.
You can then verify the installation manually by running: ``ideviceinstaller -u <udid> -i </path/to/app>`` in the terminal.

**Comment by curtissiemens** [comment]
If Appium comes with ideviceinstaller - why not the latest version?
It makes sense to either remove ideviceinstaller from the Appium package, or have the most recent version.
Because if you don't have ideviceinstaller installed locally you pick up the older version inside the appium package & get errors - so you have to install ideviceinstaller yourself anyway.

**Comment by Jonahss** [comment]
@curtissiemens Yes definitely. I'll create an issue for that. iOS real device support for appium needs some refreshing, and that's something I'm working on now :)

**Comment by Jonahss** [comment]
created #4867

**Pull request merged**
