### PR TITLE
receiveAsyncResponse make returnedFromExecuteAtom into Boolean

### PR DESCRIPTION
**Pull request by teragoon**
After "receiveAsyncResponse", "lookForAlert" into infinite loop

### CODE REVIEW

**Comment by jlipps** [comment]
Hi @teragoon I'm not sure I understand. It looks like the whole point of the existing code is to stop an infinite loop. Are you saying it's causing one?

**Comment by teragoon** [comment]
hi @jlipps 
i will explain code
```javascript
//ios.js
  this.returnedFromExecuteAtom = {};

//ios-controller.js
iOSController.executeAtom = function (atom, args, cb, alwaysDefaultFrame) {
  this.returnedFromExecuteAtom[counter] = false; // typeof(returnedFromExecuteAtom) = object
  ....
}
iOSController.executeAtomAsync = function (atom, args, responseUrl, cb) {
  this.returnedFromExecuteAtom[counter] = false; // typeof(returnedFromExecuteAtom) = object
  ....
}
iOSController.receiveAsyncResponse = function (asyncResponse) {
  this.returnedFromExecuteAtom = true; // typeof(returnedFromExecuteAtom) = boolean
  ....
}
iOSController.lookForAlert = function (cb, counter, looks, timeout) {
        if (!this.returnedFromExecuteAtom[counter] && looks < 11 && !this.selectingNewPage) {
   ....
}
//Test Code
var returnedFromExecuteAtom = {}
returnedFromExecuteAtom[0] = true // typeof(returnedFromExecuteAtom[0])  = object
returnedFromExecuteAtom[1] = false // typeof(returnedFromExecuteAtom[1])  = object
!returnedFromExecuteAtom[0] // false
!returnedFromExecuteAtom[1] // true
returnedFromExecuteAtom = true // typeof(returnedFromExecuteAtom)  = boolean
!returnedFromExecuteAtom // false
returnedFromExecuteAtom[3] = true // typeof(returnedFromExecuteAtom[3]) = undefined
!returnedFromExecuteAtom[3] // true <-- ERROR
```

I know if we do like "this.returnedFromExecuteAtom[counter] =true" in receiveAsyncResponse,
it will be best way.
but I think it will make change many things, so I couldn't do it right now.

**Comment by jlipps** [comment]
I'm going to close this for now @teragoon but I'm going to create a bug issue that tracks this so we can fix it.

**Comment by teragoon** [comment]
@jlipps Thank for your concern. I should have created a bug.

**Pull request closed without merging**
