### PR TITLE
Explain how to generate docs

### PR DESCRIPTION
**Pull request by dpgraham**

### CODE REVIEW

**Review by jlipps — APPROVED** [review]

**Comment by imurchie** [comment]
Following this doesn't seem to work for me. After pulling the latest from the `appium.io` repo, I get
```
$ node --version
v8.10.0
$ npm --version
5.6.0
$ npm run build:docs:local

> appium.io@1.0.0 build:docs:local /Users/isaacmurchie/code/appium.io
> cross-env BUILD_LOCAL_DOCS=true npm run build:docs


> appium.io@1.0.0 build:docs /Users/isaacmurchie/code/appium.io
> rimraf docs/ && babel-node scripts/repo.js && bundle exec jekyll build

{ Error: Cannot find module '/Users/isaacmurchie/code/appium.io/docs/toc.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at _callee6$ (/Users/isaacmurchie/code/appium.io/scripts/repo.js:383:23)
    at tryCatch (/Users/isaacmurchie/code/appium.io/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/isaacmurchie/code/appium.io/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/isaacmurchie/code/appium.io/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/isaacmurchie/code/appium.io/scripts/repo.js:531:191)
    at /Users/isaacmurchie/code/appium.io/scripts/repo.js:531:361
    at <anonymous> code: 'MODULE_NOT_FOUND' }
Configuration file: /Users/isaacmurchie/code/appium.io/_config.yml
            Source: /Users/isaacmurchie/code/appium.io
       Destination: /Users/isaacmurchie/code/appium.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 146.764 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by dpgraham** [comment]
@imurchie You have to set an env called $LOCAL_APPIUM which points to your Appium git repo. It looks like yours might be set to the wrong location.

**Comment by imurchie** [comment]
It would help if that were in the documentation being added.

**Comment by imurchie** [comment]
I still get errors:
```
$ LOCAL_APPIUM=/Users/isaacmurchie/code/appium npm run build:docs:local

> appium.io@1.0.0 build:docs:local /Users/isaacmurchie/code/appium.io
> cross-env BUILD_LOCAL_DOCS=true npm run build:docs


> appium.io@1.0.0 build:docs /Users/isaacmurchie/code/appium.io
> rimraf docs/ && babel-node scripts/repo.js && bundle exec jekyll build

dbug APPIUM.IO Building HTML docs from Markdown /Users/isaacmurchie/code/appium/docs
Could not build Command 'mkdocs build --site-dir /Users/isaacmurchie/code/appium.io/docs/en' exited with code 1
Reason: WARNING -  Config value: 'theme_dir'. Warning: The configuration option {0} has been deprecated and will be removed in a future release of MkDocs.
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /Users/isaacmurchie/code/appium.io/docs/en
WARNING -  The page "about-appium/intro.md" contained a hyperlink to "docs/en/about-appium/platform-support.md" which is not listed in the "pages" configuration.
WARNING -  The page "about-appium/intro.md" contained a hyperlink to "docs/en/writing-running-appium/caps.md" which is not listed in the "pages" configuration.
WARNING -  The page "about-appium/intro.md" contained a hyperlink to "docs/en/contributing-to-appium/appium-from-source.md" which is not listed in the "pages" configuration.
WARNING -  The page "about-appium/intro.md" contained a hyperlink to "docs/en/about-appium/appium-clients.md" which is not listed in the "pages" configuration.
WARNING -  The page "about-appium/intro.md" contained a hyperlink to "docs/en/about-appium/getting-started.md" which is not listed in the "pages" configuration.
ERROR   -  Error building page about-appium/intro.md
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    load_entry_point('mkdocs==0.17.3', 'console_scripts', 'mkdocs')()
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/mkdocs/commands/build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/mkdocs/commands/build.py", line 150, in _build_page
    template = env.get_template('main.html')
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main.html

{ Error: Command 'mkdocs build --site-dir /Users/isaacmurchie/code/appium.io/docs/en' exited with code 1
    at ChildProcess.<anonymous> (/Users/isaacmurchie/code/appium.io/node_modules/teen_process/lib/teen_process.js:97:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  stdout: '',
  stderr: 'WARNING -  Config value: \'theme_dir\'. Warning: The configuration option {0} has been deprecated and will be removed in a future release of MkDocs. \nINFO    -  Cleaning site directory \nINFO    -  Building documentation to directory: /Users/isaacmurchie/code/appium.io/docs/en \nWARNING -  The page "about-appium/intro.md" contained a hyperlink to "docs/en/about-appium/platform-support.md" which is not listed in the "pages" configuration. \nWARNING -  The page "about-appium/intro.md" contained a hyperlink to "docs/en/writing-running-appium/caps.md" which is not listed in the "pages" configuration. \nWARNING -  The page "about-appium/intro.md" contained a hyperlink to "docs/en/contributing-to-appium/appium-from-source.md" which is not listed in the "pages" configuration. \nWARNING -  The page "about-appium/intro.md" contained a hyperlink to "docs/en/about-appium/appium-clients.md" which is not listed in the "pages" configuration. \nWARNING -  The page "about-appium/intro.md" contained a hyperlink to "docs/en/about-appium/getting-started.md" which is not listed in the "pages" configuration. \nERROR   -  Error building page about-appium/intro.md \nTraceback (most recent call last):\n  File "/usr/local/bin/mkdocs", line 11, in <module>\n    load_entry_point(\'mkdocs==0.17.3\', \'console_scripts\', \'mkdocs\')()\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/click/core.py", line 722, in __call__\n    return self.main(*args, **kwargs)\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/click/core.py", line 697, in main\n    rv = self.invoke(ctx)\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/click/core.py", line 1066, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/click/core.py", line 895, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/click/core.py", line 535, in invoke\n    return callback(*args, **kwargs)\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/mkdocs/__main__.py", line 156, in build_command\n    ), dirty=not clean)\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/mkdocs/commands/build.py", line 282, in build\n    build_pages(config, dirty=dirty)\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/mkdocs/commands/build.py", line 242, in build_pages\n    _build_page(page, config, site_navigation, env)\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/mkdocs/commands/build.py", line 150, in _build_page\n    template = env.get_template(\'main.html\')\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template\n    return self._load_template(name, self.make_globals(globals))\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template\n    template = self.loader.load(self, name, globals)\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "/usr/local/Cellar/mkdocs/0.17.3/libexec/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: main.html\n',
  code: 1 }
Configuration file: /Users/isaacmurchie/code/appium.io/_config.yml
            Source: /Users/isaacmurchie/code/appium.io
       Destination: /Users/isaacmurchie/code/appium.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 131.194 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by dpgraham** [comment]
@imurchie I updated the docs to make it more detailed.

I also changed it so that in the RELEASE you have the option to either update the docs or put in an issue to have the docs be updated.

**Review by imurchie — APPROVED** [review]

**Pull request merged**
