### PR TITLE
fixed npm commands to work with appium-gulp-plugins

### PR DESCRIPTION
**Pull request by christian-bromann**
Adapted NPM commands according to other packages

ping @imurchie

### CODE REVIEW

**Comment by halkeye** [comment]
npm run automatically adds ./node_modules/.bin to path
so you shouldn’t need that bit

**Comment by christian-bromann** [comment]
thanks @halkeye 
(interesting, did not know that)

**Comment by imurchie** [comment]
Can you squash the commits. Then we can merge. Thanks!

**Comment by christian-bromann** [comment]
@imurchie done!

**Comment by imurchie** [comment]
Thanks! And welcome to Appium!

**Pull request merged**
