### PR TITLE
The original bplist parser  cannot parse chinese well

### PR DESCRIPTION
**Pull request by lihuazhang**
swapBytes should not ruin the original buffer

### CODE REVIEW

**Comment by jlipps** [comment]
In general I'd like to pull from NPM and not GitHub. Have you tried submitting the patch to the original project?

**Comment by lihuazhang** [comment]
@jlipps I've submittd the patch to the original project.

**Comment by lihuazhang** [comment]
@jlipps https://github.com/joeferner/node-bplist-parser/ has merge my pull request. You can update the version to v0.1.0

**Comment by jlipps** [comment]
ok, it's been updated in master. thanks @lihuazhang!

**Pull request closed without merging**
