### PR TITLE
Document 'startIWDP' desired capability

### PR DESCRIPTION
**Pull request by dpgraham**

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Review by jlipps — COMMENTED** [review]
can we give a little more context? Something like:

> Run an instance of ios_webkit_debug_proxy automatically inside of Appium rather than requiring that the user run it on their own outside of Appium.

**Comment by dpgraham** [comment]
I updated it. I agree it's better to give the context of why you'd use `startIWDP`.

**Pull request closed without merging**
