### PR TITLE
updated websocket dependency to resolve remote memory disclosure

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
FYI https://nodesecurity.io/advisories/ws_buffer-leak

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
Hope this will resolve #5999

**Comment by SrinivasanTarget** [comment]
https://gist.github.com/c0nrad/e92005446c480707a74a

**Comment by SrinivasanTarget** [comment]
@imurchie I hope this will give more info https://david-dm.org/appium/appium

**Comment by imurchie** [comment]
Ah! Thanks.

**Comment by SrinivasanTarget** [comment]
(y)

**Comment by imurchie** [comment]
Merged. Thanks for this!

I've also updated `appium-remote-debugger`, which is the only place we use `ws` in 1.5.

**Comment by SrinivasanTarget** [comment]
yup welcome @imurchie

**Pull request merged**
