### PR TITLE
Add doctor checks to appium repo

### PR DESCRIPTION
**Pull request by rkavalap**
## Proposed changes

Adding appium-doctor checks to appium repo. 

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by imurchie** [comment]
Is the intention of this to get rid of `appium-doctor`? Or just to have some sanity checks on launch of the server? If

**Comment by rkavalap** [comment]
@imurchie Not exactly getting rid of appium-doctor for now. Because this PR does not autofix some of the issues which appium-doctor does. At least these cover all the sanity check scenarios within appium-doctor

**Comment by imurchie** [comment]
I think it would be better, then, to refactor the code in `appium-doctor` so that it can be imported and used here, rather than duplicated.

**Review by jlipps — COMMENTED** [review]
yes, if we're going to use appium-doctor code in appium, it should be imported (which might mean appium-doctor must first be refactored to have the appropriate exports)

**Review by jlipps — COMMENTED** [review]
i don't understand the 'docChecks' dir. isn't this code just taken from appium-doctor? i think we should include appium-doctor as a dependency rather than duplicating its code.

or are you working on https://github.com/appium/appium/issues/7474?

**Comment by rkavalap** [comment]
Yes I intended this for #7474

**Comment by jlipps** [comment]
going to close this since we want to import the code as a library rather than copy the code to this project.

**Pull request closed without merging**
