### PR TITLE
Update commands for the Ruby client

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Proposed changes

ref: https://github.com/appium/ruby_lib/issues/671

- Update commands for the Ruby client
    - Update the reference
    - Update the commands
    - Update the followings because they weren't described for page-index and replace-value.
        - `commands-yml/commands/element/attributes/page-index.yml`
        - `commands-yml/commands/element/attributes/replace-value.yml`

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by KazuCocoa** [comment]
I'd love you to check the following, especially.

> Update the followings because they weren't described for page-index and replace-value.
>    - commands-yml/commands/element/attributes/page-index.yml
>    - commands-yml/commands/element/attributes/replace-value.yml

**Comment by dpgraham** [comment]
Awesome! Thanks, I'll have a look at this soon.

**Review by dpgraham — APPROVED** [review]

**Comment by KazuCocoa** [comment]
thanks a lot!

**Comment by dpgraham** [comment]
Thank you!

**Pull request merged**
