### PR TITLE
Add appName cap to docs

### PR DESCRIPTION
**Pull request by imurchie**
Final step in getting the iOS background fix of @wuhao5 into 1.5.

### CODE REVIEW

**Comment by wuhao5** [comment]
@imurchie , @jzha mentioned [here](https://github.com/appium/appium/issues/5737#issuecomment-169841402) another better approach, so I tried it out real quick,

[git compare](https://github.com/appium/appium/compare/master...wuhao5:master)

I think it works better because there is no need to deal with the applescript and accessibility permissions. Can you take a look at it too? I can send another PR for it if you prefer.

**Comment by imurchie** [comment]
What is it doing?

**Comment by wuhao5** [comment]
it is basically this:

```javascript
try {
   target.deactivateAppForDuration(seconds);
} catch (e) {
   var point = target.frontMostApp().mainWindow().scrollViews()[0].elements()[appName].hitpoint();
   target.tap(point);
}
```

it catches the exception but meantime, the script can still access to the element in the sprintboard, so it taps on it to open the app again.

**Comment by wuhao5** [comment]
asides, thanks for this! :+1:

**Comment by imurchie** [comment]
Does this work for you? It backgrounds the app for me, but does not foreground it again.

**Comment by wuhao5** [comment]
Hmmm, it worked for me, tested on UICatalog.app and iPhone 6/9.2 simulator.

**Comment by imurchie** [comment]
Can you post the log for the background call? So I can see what Instruments is doing. Thanks!

**Comment by jzha** [comment]
It is really nice to fix this issue on iOS9. Thanks!

**Comment by jzha** [comment]
Scrolling also throws `WebDriverException`, not sure if you have already fixed it or not.
```java
JavascriptExecutor js = driver;
HashMap<String, String> scrollObject = new HashMap<>();
scrollObject.put("direction", direction.value());
js.executeScript("mobile: scroll", scrollObject);//this throws WebDriverException 
```

**Comment by imurchie** [comment]
When `UICatalog` is installed, is the icon on the main screen? Mine is on a second screen in the sim, so no tap point is found by the UI Automation call. Attempting to get to that screen to activate.

**Comment by wuhao5** [comment]
Ah, I remembered, at some point, some version of iOS simulator/Instrument (8.x), it fails to relaunch due to that, but it started working again on newer version.

let me post the log real quick.

**Comment by wuhao5** [comment]
it doesn't seem to capture all, but here is the log i have (iOS9.2/iPhone 6):

```
info: --> POST /wd/hub/session/f20e55ca-e087-4c7a-9730-07ab4896a6b4/appium/app/background {"seconds":4}
info: [debug] Pushing command to appium work queue: "try{au.background(4);}catch(e){target.tap(target.frontMostApp().mainWindow().scrollViews()[0].elements()['UICatalog'].hitpoint());}"
info: [debug] Sending command to instruments: try{au.background(4);}catch(e){target.tap(target.frontMostApp().mainWindow().scrollViews()[0].elements()['UICatalog'].hitpoint());}
info: [debug] [INST] 2016-01-08 18:47:52 +0000 Debug: Got new command 3 from instruments: try{au.background(4);}catch(e){target.tap(target.frontMostApp().mainWindow().scrollViews()[0].elements()['UICatalog'].hitpoint());}
info: [debug] [INST] 2016-01-08 18:47:52 +0000 Debug: evaluating try{au.background(4);}catch(e){target.tap(target.frontMostApp().mainWindow().scrollViews()[0].elements()['UICatalog'].hitpoint());}
info: [debug] [INST] 2016-01-08 18:47:52 +0000 Debug: target.deactivateAppForDuration("4")
info: [debug] [INST] 2016-01-08 18:47:53 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-01-08 18:47:53 +0000 Debug: responding with:
info: [debug] [INST] 2016-01-08 18:47:53 +0000 Debug: Running system command #4: /opt/local/bin/node /Users/hao.wu/dev/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...
info: [debug] Socket data received (28 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}
info: [debug] Responding to client with success: {"status":0,"value":false,"sessionId":"f20e55ca-e087-4c7a-9730-07ab4896a6b4"}
```

**Comment by imurchie** [comment]
It's strange. On my setup, using iOS 9.2, I never get an exception. When I move the code out of the catch block it fails because `hitpoint()` doesn't return anything, and tap can't handle it.

**Comment by wuhao5** [comment]
Oh, I lied, it didn't work for me neither :(

I just had another idea, let me try it out.

**Pull request merged**
