### PR TITLE
Remove unnecessary 'finally' block

### PR DESCRIPTION
**Pull request by dpgraham**
* Shouldn't have had finally block because then it does two checks to fall back to MJSONWP
* Also fixed outdated tests

### CODE REVIEW

**Comment by imurchie** [comment]
Any idea why the tests modified would be flakey? Were they always like that?

**Comment by dpgraham** [comment]
@imurchie They weren't flakey, they were outdated. Previously, `appium-base-driver` was incorrectly just returning the error as a message. Now, it returns errors as:

```javasript
{
  value: {message: "...", stacktrace: "...", stacktrace: "..."}
}
```

**Comment by imurchie** [comment]
Oh. but in one run it only failed once out of four in Travis, I thought.

**Comment by dpgraham** [comment]
I think the failing ones had been using base driver version 2.20.1 which we would expect to fail. 2.20.2 it should pass.

**Review by mykola-mokhnach — APPROVED** [review]

**Pull request merged**
