### PR TITLE
chore: print global

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Proposed changes

https://github.com/appium/appium/pull/15974/checks?check_run_id=3909469397 failed since npm was not able to load globally. Let me check what module is available as "global" package for now.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
cc @boneskull

**Comment by KazuCocoa** [comment]
mm
```
Run `npm audit` for details.
/opt/hostedtoolcache/node/16.11.1/x64/lib
├── corepack@0.9.0
└── npm@8.0.0
```

**Comment by jlipps** [comment]
hmm it would surprise me if `NODE_PATH: npm -g root` worked as expected, since in bash it has to be `$(npm -g root)`, i.e., the result of the expression becomes the env var. what if you just printed out `npm -g root` so we can at least see what the directory is on these VMs.

**Comment by boneskull** [comment]
an `npm i -g npm` might be good to check as well

**Pull request closed without merging**
