### PR TITLE
Don't kill the iOS simulator when running on device.

### PR DESCRIPTION
**Pull request by paymand**
Current behavior makes it impossible to work on something in the simulator while running tests on device.

### CODE REVIEW

**Comment by 0x1mason** [comment]
How critical is this issue?  Is this a nice to have or a major blocker?

**Comment by 0x1mason** [comment]
Changes lgtm.

**Comment by paymand** [comment]
It's just a nuisance and I believe it should be safe enough to merge.

**Comment by 0x1mason** [comment]
I'll merge it.  I was wondering if it was critical and needed to get added to 1.3.5 or if it can wait.  Sounds like it can wait for the next release.  Thanks.

**Pull request merged**
