### PR TITLE
Add scaleFactor capability description

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This PR is based on https://github.com/appium/appium-ios-simulator/pull/74 and https://github.com/appium/appium-xcuitest-driver/pull/282

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by imurchie** [comment]
👍

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by jlipps** [comment]
@mykola-mokhnach we really need to get your commits set to your github user, so the CLA bot is satisfied. it's also important legally. did you follow the instructions at https://help.github.com/articles/setting-your-email-in-git/? This is what I still see on your commit here for example:

screen shot 2016-11-08 at 8 58 40 am

Looks like you can either (a) add that e-mail to your github account, or (b) change the git config e-mail to match what you have for this github account

**Comment by mykola-mokhnach** [comment]
@jlipps It's my old corporate email address, which is not valid anymore, and it does not exist in my profile, since it has been replaced with a new one on wire.com domain. The problem there is that I cannot change anything on the default CLA bot input form, since all the fields are disabled for me. What else could I do?

**Comment by jlipps** [comment]
@mykola-mokhnach what you can do is change your git user on your command line, so that when you create commits and push them, it will be associated with your correct e-mail address. If you do that, then re-commit and force-push to this PR, it should show that it's been updated

**Comment by mykola-mokhnach** [comment]
Thanks for the hint @jlipps. Probably, the problem was in my local git config. I've updated the email there and resubmitted my changes.

**Comment by jlipps** [comment]
@mykola-mokhnach hmm I don't see that you've resubmitted the changes; this should do it:

```
git commit --amend -am "Add scaleFactor capability description"
git push -f <origin if that's your remote> simulator_scale
```

maybe that will freshen up the commit in this PR?

**Comment by jlipps** [comment]
oh LOL forgot this one was already merged :-)

**Pull request merged**
