### PR TITLE
refactor(support): Speed up findAppiumDependencyPackage API

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
The previous implementation used `npm list` call, which is super slow, because it reads all package dependencies

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]
lg, so is this when we start an appium process in a driver directory for example? Then appium loads the workspace.

**Comment by mykola-mokhnach** [comment]
> lg, so is this when we start an appium process in a driver directory for example? Then appium loads the workspace.

yes, this whole logic is needed for appium to understand it is a dependency of an other project, which is anyway a minority of all deployments. I see a lot of complicated code there to support that scenario, which might be essentially not really needed as it covers edge cases. Even more, I don't want it to slow down the server startup for the majority of deployment cases.

**Review by jlipps — COMMENTED** [review]
do all the cases still work after this change?

**Comment by mykola-mokhnach** [comment]
> do all the cases still work after this change?

One case does not work - where appium is included as `file:` dependency. I assume it's ok to have it like that because:
- One can always provide APPIMU_HOME manually instead of autodetecting it
- It's an edge case

**Comment by jlipps** [comment]
ok. as long as it works when appium is a dev/peer dep and we're in a driver repo doing driver development, that should be fine!

**Pull request merged**
