### PR TITLE
Add changelog and bump to 1.5.2

### PR DESCRIPTION
**Pull request by imurchie**
In preparation for 1.5.2 release.

### CODE REVIEW

**Comment by imurchie** [comment]
Travis is not starting jobs. Tested locally. Merging.

**Comment by amaharana** [comment]
Can we get the multiple wait activity fix in 1.5.2 release? 
https://github.com/appium/appium-adb/pull/155
I'll try and get the follow-up commit in today - waiting on internal approval.

**Comment by imurchie** [comment]
It seems unlikely, unless it gets in very soon.

**Comment by amaharana** [comment]
Pushed it already. In the same pull request.
https://github.com/appium/appium-adb/pull/155/commits/99d2d9f4a4d8f3e3e204f7eb18c15f380506ca49

**Pull request merged**
