### PR TITLE
Location services fix

### PR DESCRIPTION
**Pull request by siriwit**
- Supported allow location service for 8.x platform.
- Fixed location service for 7.x platform.

### CODE REVIEW

**Comment by jlipps** [comment]
@siriwit I'm :+1: for this change, but can you please squash your commits so there's just one here (no merge commit)

**Comment by siriwit** [comment]
@jlipps thank you for your reply. I'm quite new in Github. So, how can I do that?
You mean I should commit for each change?

Note: I have 2 changes with 1 commit.

**Comment by moizjv** [comment]
@siriwit  [documentation for squashing](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by moizjv** [comment]
@siriwit ping

**Comment by siriwit** [comment]
yesterday, I tried to squash my commit but I doesn't work for me. I'm not sure if I missed something or not. For now, it seems the easiest way for me is create a pull request again with one commit 
or 
anyone of you can help me?

**Comment by siriwit** [comment]
Finally, Git expert helped me. So, my commit left only one.
Could you guys merge my patch?

**Pull request merged**
