### PR TITLE
Remove default ChromeDriver port in arg parse

### PR DESCRIPTION
**Pull request by midopa**
## Proposed changes

Let lower level Android driver pick a random free port for Chrome driver if the user doesn't give an explicit port. This will allow parallel browser-based Android tests on the same machine.

WRT https://github.com/appium/appium-android-driver/issues/176
## Types of changes

What types of changes does your code introduce to Appium?
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Checklist
- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by jlipps** [comment]
👍  however we should wait to merge this until we've also updated the `android-driver` entry in package.json with a version of android-driver that has the appropriate changes

**Comment by imurchie** [comment]
The changes were published in `appium-android-driver@1.10.19`, so this can be updated (adding 1.10.19 as the lowest version for `appium-android-driver` in `package.json`) and we can get it in.

**Comment by imurchie** [comment]
@midopa We'd like to get this in. Can you update the `package.json` so `appium-android-driver` requires at least 1.10.19? Without that there is a possibility that no port would be assigned and CD proxying would fail altogether.

**Comment by midopa** [comment]
Sure. Update coming up

**Comment by midopa** [comment]
Done

**Comment by imurchie** [comment]
Awesome! Thanks!

**Pull request merged**
