### PR TITLE
README: cross-domain iframes

### PR DESCRIPTION
**Pull request by scottdixon-zz**
## Proposed changes

Explanation of same-origin policy workaround for subdomains.
## Types of changes

Docs only
## Checklist
- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by imurchie** [comment]
Looks good to me!

**Comment by jlipps** [comment]
\o/

**Pull request merged**
