### PR TITLE
ci: drop nodejs 12, add 17

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Proposed changes

as appium 2 will be over nodejs14.
I'll check other nodejs ci version stuff later

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by boneskull** [comment]
Also, I may want to request we delay merging this.  I will get back to you...

**Comment by boneskull** [comment]
_Also_, in the future when/if `appium-desktop` runs Appium 2, when we drop support for EOL Node versions, we should make sure it won't negatively impact `appium-desktop`

**Comment by jlipps** [comment]
> Also, in the future when/if appium-desktop runs Appium 2, when we drop support for EOL Node versions, we should make sure it won't negatively impact appium-desktop

Good point. As long as we're using a relatively recent electron, it should be using a relatively recent Node.

**Comment by KazuCocoa** [comment]
yes, i just created this to not forget this task... and i remember this when i saw nodejs12 failure.

**Comment by boneskull** [comment]
We are OK with dropping Node.js v12 support

**Pull request merged**
