### PR TITLE
Document various reset strategies

### PR DESCRIPTION
**Pull request by dpgraham**
(reviewers @jlipps @imurchie)

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Review by jlipps — APPROVED** [review]
huzzah! my only other comment is that maybe this doc could be linked from some other doc to enable others to find it?

**Review by imurchie — APPROVED** [review]

**Comment by dpgraham** [comment]
I made a link from README.md

Let me know if that's okay, @jlipps and then I'll merge it.

**Review by jlipps — COMMENTED** [review]
actually i don't think we should put it there. after thinking more, i think we should link it from `noReset` and `fullReset` in `caps.md`

**Comment by dpgraham** [comment]
Changes made

**Pull request merged**
