### PR TITLE
Updated Selendroid to 0.15.0.

### PR DESCRIPTION
**Pull request by paymand**
The compile fix for Cordova error works on Linux and Mac. Haven't tested on Windows.

### CODE REVIEW

**Comment by paymand** [comment]
Retest this please

**Comment by jlipps** [comment]
:+1: and when you say "works" you mean you ran the selendroid tests in our test suite?

**Comment by paymand** [comment]
@jlipps: No, I was referring to the compile error with Cordova. I thought the selendriod tests are run by the CI.

**Comment by jlipps** [comment]
maybe they are now!

**Comment by paymand** [comment]
@sebv: ^

**Comment by jlipps** [comment]
@paymand looks like only the unit tests are run in CI. i'll run some tests to see if this works.

**Comment by paymand** [comment]
Ah, OK. I hope they work. I'll try to remember this next time.

**Comment by sebv** [comment]
Not yet, am building Mac VMs right now.

**Comment by jlipps** [comment]
got lots of errors. safe to say this isn't working right now.

**Comment by jlipps** [comment]
(or at least, isn't working with all of our tests)

**Comment by jlipps** [comment]
#4688

**Pull request merged**
