### PR TITLE
Fix iOS simulator selector for Xcode 7

### PR DESCRIPTION
**Pull request by ericwengelking**

### CODE REVIEW

**Comment by ericwengelking** [comment]
@jlipps this is related to issue https://github.com/appium/appium/issues/5233

**Comment by ericwengelking** [comment]
Also related to https://github.com/appium/appium/issues/5488

**Comment by ericwengelking** [comment]
I have also tested this change against Xcode 7.0 GM seed and Xcode 7.1 beta 1 and it still works.

**Comment by jlipps** [comment]
thanks @ericwengelking!

cc @moizjv and @imurchie; this will need to get into the appium-ios-driver, and @moizjv this will be relevant for you as well

**Comment by hojbota** [comment]
I am still getting this error with Appium Version 1.4.8 and Xcode Version 7.1 beta (7B60)

**Comment by imurchie** [comment]
@hojbota this is not in a released version yet. You'll need to run from source in order to get it.

**Comment by hojbota** [comment]
ah right, sry...

**Comment by ankit154** [comment]
When can we expect this fix in a released version.Any estimates on that?

**Comment by imurchie** [comment]
It should be out now.

**Pull request merged**
