### PR TITLE
Add Tizen Driver

### PR DESCRIPTION
**Pull request by flyofsky**
## Proposed changes
 - Added Tizen Driver to support Appium in Tizen.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by imurchie — APPROVED** [review]

**Review by jlipps — APPROVED** [review]
This is wonderful @flyofsky! I've been hoping for a Tizen driver for years, and have been trying to find someone at Samsung to talk to about implementing one. Looks like you all have been working on it already.

I think the next steps to this becoming first-class are:

1. Have the Appium team review the Tizen driver code to make sure it's following appropriate conventions
2. Write documentation for how to use the Tizen driver from a test author perspective, and add to appropriate places in the Appium docs.

I'm fine to merge this now and make it available as a beta without the above, however.

**Comment by imurchie** [comment]
We can get this in once the CLA is signed by both contributors.

**Comment by dpgraham** [comment]
We can disregard the CI failure. I'm going to put in a PR that makes it so that it only builds the bundle on master.

**Comment by rookiejava** [comment]
@imurchie we all already signed the CLA. could anyone try @jsf-clabot again?

**Comment by imurchie** [comment]
Awesome! Thanks!

**Pull request merged**
