### PR TITLE
docs(1.x): Add missing parameter to start-activity.

### PR DESCRIPTION
**Pull request by garg3133**
## Proposed changes

Add missing `appWaitActivity` parameter to start-activity. This parameter is present in appium-base-dir's [routes.js](https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L536) file but is missing from the docs.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the CLA
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by boneskull** [comment]
@jlipps are we accepting updates to v1.x docs?

**Comment by jlipps** [comment]
i guess it doesn't hurt. it will probably never be published though.

**Comment by garg3133** [comment]
Ohh, I only made this change because I wanted to reference somewhere all the json parameters that the `startActivity` command accepts. But it's okay if it won't be published, I can just add the link to the modified yml file in that case instead of the Appium website until these commands are available on Appium 2.0 docs.

**Comment by jlipps** [comment]
> I can just add the link to the modified yml

The yml files don't exist in the 2.0 branch, so should not be linked to

> until these commands are available on Appium 2.0 docs

The Appium 2.0 docs will not list driver-specific commands at all. Instead, the drivers will have all the docs for their own commands. The best way to ensure that this parameter is mentioned in the uiautomator2 doc moving forward is to send a PR to that repo

**Comment by boneskull** [comment]
Should this be closed?

**Comment by garg3133** [comment]
> The best way to ensure that this parameter is mentioned in the uiautomator2 doc moving forward is to send a PR to that repo

@jlipps I would love to do that but I couldn't find the docs for the commands anywhere in the [appium-uiautomator2-driver](https://github.com/appium/appium-uiautomator2-driver) repo. I couldn't even find the implementation for the `startActivity` method but the [README](https://github.com/appium/appium-uiautomator2-driver#applications-management) says that it's there.

Can you please direct me where I can look for the doc for `startActivity` command or even the implementation of the same? From [here](https://github.com/appium/appium-uiautomator2-driver/blob/783cec6dd8945896dbbfd565d7c0223c0b05166e/lib/driver.js#L77), it seems to me that the command is not being proxied to `appium-uiautomator2-server` and it doesn't make sense to proxy it to `chromedriver`. I also looked into `appium-adb` but that isn't really a server but just a library. So, how does this and similar commands work?

**Comment by jlipps** [comment]
@garg3133 i think probably in this case we should just do nothing. pretty soon the uiautomator2 command docs will be auto generated from the implementation code, so all the parameters will be properly documented.

**Pull request closed without merging**
