### PR TITLE
add deviceType for tvOS support instead of adding a new platform name

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Proposed changes

I've introduced tvOS in https://github.com/appium/appium/pull/12401/files
after a while, I considered adding `deviceType` was better than adding new platform since the tv was kind of new device/product in iOS(Apple) platform.

If we start considering such deviceType, we probably can think device variations such as watch, tv etc even if they are Android/iOS/Windows etc platform.

Will update xcuitest-driver and bump the version in package.json in this repository

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
@imurchie Are you ok with this change?

**Review by imurchie — COMMENTED** [review]
I'm not sure I understand the reasoning behind this. `iOS` and `tvOS` are different platforms, even if both handled by XCUITest.

Why add another capability?

**Comment by KazuCocoa** [comment]
When I managed android/android TV/fire TV  and used Appium before, I handled them like device type(similar to this deviceType caps) in my env. The name of xxxTv changed (Google TV => Android TV) once. The TV also needed different build like ios and tvOS applications. 
I was not sure tvOS name will change like the above case, but thinking as below was better, I thought. 


- Run tests on android platform on TV device
- Run tests on android platform on firetv device
- Run tests on ios(apple) platform on TV device

**Comment by imurchie** [comment]
The handling at the AppiumDriver level will be gone once 2.0 is implemented, so it is not really a concern.

My main concern is that iOS and tvOS are entirely different platforms, not versions of each other. I strongly object to the concept of `deviceType` in this case (Android may be a different thing, since there the tv system _is_ derived from the phone system).

**Comment by KazuCocoa** [comment]
I could understand 👌
Thanks for your opinion!

**Pull request closed without merging**
