### PR TITLE
chore(support,opencv): Override unsecure jpeg-js module for jimp imports

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
https://github.com/oliver-moran/jimp/issues/1088#issuecomment-1223373894

### CODE REVIEW

**Comment by boneskull** [comment]
I'd expect to see a `package-lock.json` update with this

**Comment by mykola-mokhnach** [comment]
> I'd expect to see a `package-lock.json` update with this

Could you please explain how to reach that?
Currently the npm audit already complains about major security issue when installing Appium. Also there is no way to get the original jimp module updated/patched as it is not maintained. 
For now I can only see this trick as the possible way to resolve the security issue and eliminate the corresponding NPM warning

**Comment by boneskull** [comment]
@mykola-mokhnach I mean, if you have working overrides in there and you `npm install`, then those overrides should reflect in `package-lock.json`.  It should have been updated and committed

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach I mean, if you have working overrides in there and you `npm install`, then those overrides should reflect in `package-lock.json`. It should have been updated and committed

Updated package-lock and also added one more override to the main repo json according ito https://github.com/npm/cli/issues/4232#issuecomment-1197584479

**Comment by mykola-mokhnach** [comment]
@boneskull 

Btw tsc started complaining about some new errors after rebase:

```
> appium-monorepo@0.0.0 build:types
> tsc -b

packages/appium/build/lib/appium.d.ts:200:5 - error TS2416: Property 'getProxyAvoidList' in type 'AppiumDriver' is not assignable to the same property in base type 'DriverCore'.
  Type '(sessionId: any) => [string, RegExp][]' is not assignable to type '(sessionId: string) => RouteMatcher[]'.
    Type '[string, RegExp][]' is not assignable to type 'RouteMatcher[]'.
      Type '[string, RegExp]' is not assignable to type 'RouteMatcher'.
        Type at position 0 in source is not compatible with type at position 0 in target.
          Type 'string' is not assignable to type 'HTTPMethod'.

200     getProxyAvoidList(sessionId: any): [string, RegExp][];
        ~~~~~~~~~~~~~~~~~

packages/appium/lib/config-file.js:86:60 - error TS2345: Argument of type 'ErrorObject<string, Record<string, any>, any>[]' is not assignable to parameter of type 'ErrorObject[]'.
  Property 'dataPath' is missing in type 'ErrorObject<string, Record<string, any>, any>' but required in type 'ErrorObject'.

86   return betterAjvErrors(getSchema(opts.schemaId), config, errors, {
                                                              ~~~~~~

  node_modules/ajv/lib/ajv.d.ts:300:5
    300     dataPath: string;
            ~~~~~~~~
    'dataPath' is declared here.


Found 2 errors.
```

**Review by jlipps — APPROVED** [review]
there's no fix in jimp itself yet?

**Comment by boneskull** [comment]
@jlipps jimp won't get any fixes. 

that type error is my fault, will fix

**Comment by boneskull** [comment]
@jlipps see the "we need to talk about jimp" issue. on mobile so apparently can't easily reference issues in a comment

**Comment by boneskull** [comment]
I'm sending a PR to this branch which fixes the overrides.  In my version of `npm`, this change didn't actually _do_ anything.  If it had done something, `package-lock.json` should have been updated.  I'm not sure where the latest change to `package-lock.json` came from...

**Comment by mykola-mokhnach** [comment]
> I'm sending a PR to this branch which fixes the overrides. In my version of `npm`, this change didn't actually _do_ anything. If it had done something, `package-lock.json` should have been updated. I'm not sure where the latest change to `package-lock.json` came from...

There was a bug in npm related to dependency overrides: https://github.com/npm/cli/issues/4232#issuecomment-1197584479

Simply make sure your npm is up to date

**Comment by boneskull** [comment]
See https://github.com/mykola-mokhnach/appium/pull/1

**Comment by boneskull** [comment]
My npm is at latest

**Pull request closed without merging**
