### PR TITLE
Start IWDP and calendar access authorized documentation

### PR DESCRIPTION
**Pull request by dpgraham**
For some reason, this pull request was never merged. It documents two of the capabilities startIWDP and calendarAccessAuthroizedt

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by jlipps** [comment]
@dpgraham can you fix conflicts?

**Comment by dpgraham** [comment]
I know why this was closed now. This should be documented in xcuitest-driver page.

Made a new PR: https://github.com/appium/appium-xcuitest-driver/pull/453

**Pull request closed without merging**
