### PR TITLE
adding support for importing user defined javascript libraries

### PR DESCRIPTION
**Pull request by fernyb**
Depends on https://github.com/appium/appium-uiauto/pull/73

### CODE REVIEW

**Comment by jlipps** [comment]
yeah, I think just sending all the custom stuff you need as an initial executeScript at the beginning of your test should be enough, right?

**Comment by fernyb** [comment]
@jlipps I was doing just that. Reading the file and using execute_script to load the javascript code, all was fine until it got large enough and started to fail. I tried  "#import" within execute_script and that fails when it does evals.
And "#import" works fine within Instruments and when it's in dynamic-bootstrap.js

**Comment by jlipps** [comment]
@fernyb, interesting, '#import' broke at one point. i guess they added it back in.

if sending via execute_script doesn't work, i guess having the ability to add your own library files via an import makes sense.

**Comment by imurchie** [comment]
Unfortunately, in the shuffle of Appium 1.5, this PR got very messed up. If the problem that it was meant to solve persists in 1.5, can you either (a) open an issue explaining the problem and the solution, or (b) open a new PR?

We apologize for the mess up. :(

**Pull request closed without merging**
