### PR TITLE
chore: remove authorize-ios from package

### LINKED ISSUE #14901: Appium install returns a non-zero exit code with NPM7
## The problem

Appium fails to install or at least returns a non-zero exit code while installing

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.0
* Last Appium version that did not exhibit the issue (if applicable): Unsure - maybe 1.11.0
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): v15.2.1
* Npm or Yarn package manager: npm@7.0.10
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: N/A
* Appium CLI or Appium.app|exe: CLI

## Details

When running the following commands on a fresh OS Catalina install:
```
brew install node
npm install -g appium
```
it errors with
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

However - if I go to run appium it does appear to launch. We're installing appium through Packer so the fact that it errors but is still installed is not ideal. I'm also not 100% convinced the install is complete because of this error but I can't be sure.

Someone else saw this same behavior [here](https://stackoverflow.com/questions/64655932/bin-authorize-ios-not-found-when-installing-appium-using-npm-install-g-appium)

## Other notable things:
- Since we're doing this with packer I can say that the OS is new and the test is repeatable
- I tried downgrading node but that does not seem to have an effect until v1.11.0. It also doesn't seem like I can update it to the latest

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Proposed changes

closes https://github.com/appium/appium/issues/14901#issuecomment-743762334

We no longer need the script in xcuitest.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by mykola-mokhnach — APPROVED** [review]
Thanks @KazuCocoa

**Comment by KazuCocoa** [comment]
Will try to push a new beta following https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/release-appium.md#publish-to-ga 💪

**Comment by mykola-mokhnach** [comment]
How about we try to also push a fix for arm64 arch for WDA and include it to the new beta as well?

**Comment by KazuCocoa** [comment]
Yea, good idea

**Pull request merged**
