### PR TITLE
chore: merge base-driver master (de7e41b) to base-driver for 2.0

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Proposed changes

https://github.com/appium/appium-base-driver/pull/485 to 2.0 branch

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by jlipps** [comment]
thanks @KazuCocoa ! a couple notes:

1. with the monorepo, we should use scopes for our conventional commits. like "chore(base-driver): xxx", so that automatic changelog generation can work for specific packages.
2. in thinking about this kind of chore, i worry about the changelog generation. the commit here basically just says there was a merge from some other repo. but that is not a description of the work that has been done. do you think it makes sense to create the commit as a real commit would be instead? something like "fix(base-driver): remove unused location helper functions" or whatever this change is actually about.

**Comment by KazuCocoa** [comment]
ah, gotcha > 1.

Yea, agree with the 2 as well. Let me revert this PR and create the same one by tweaking this commit message later. This step should be better than force push, I believe.

**Comment by jlipps** [comment]
sounds good! @boneskull any other thoughts? I know you've thought through this the most of us probably.

**Comment by boneskull** [comment]
yes, I think that's fair: just use a commit message scope associated with the package. 

this should probably be `chore`. 

I think it may be a good idea to instruct Lerna to only bump versions when it encounters a `fix` or `feat`...  

anyway, I can create a doc with some proposed conventions and send a PR.

**Pull request merged**
