### PR TITLE
docs: Update chromedriver discovery details

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Proposed changes

Address https://github.com/appium/appium/issues/14516

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Review by sakibguy — COMMENTED** [review]
good work

**Review by jlipps — COMMENTED** [review]
can we apply this to the 2.0 branch as well?

**Comment by KazuCocoa** [comment]
im thinking to apply all changes in `docs` to 2.0 branch after 1.22 release.
(I guess this is already in the branch tho)

**Comment by jlipps** [comment]
OK great. let's remember to do that before doing any big docs refactors then.

**Pull request merged**
