### PR TITLE
Security check to adhere to node security policies

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
## Proposed changes

This will now check for any security issues on the node modules that we use in our appium project before we publish this to wider audience through npm. Also this enables us to adhere the node security guidelines as well.
## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
## Further comments

In past i have reported there are modules that we used which are not maintained or doesn't comply node security standards.If we comply those node security standards, its an added advantage for us wherein it can be used further in Banking domains as well. Thanks.

### CODE REVIEW

**Comment by moizjv** [comment]
Can one of the admins verify this patch?

**Comment by SrinivasanTarget** [comment]
@imurchie callback is never called so please help me in fixing it up.

**Comment by imurchie** [comment]
The callback is called on my system. But `nsp` complains if there is no `package` field in the invocation.

```shell
👻 ➤ gulp nsp
[15:22:46] Using gulpfile ~/code/appium-repos/appium/gulpfile.js
[15:22:46] Starting 'nsp'...
[15:22:46] 'nsp' errored after 8.36 ms
[15:22:46] Error in plugin 'gulp-nsp'
Message:
    (+) Error: package.json is required
```

**Comment by SrinivasanTarget** [comment]
@imurchie It needs either package or shrinkwrap so i pointed to shrinkwrap but not sure why is it throwing the error for package.Also do you want me to port this to appium-gulp-plugins?

**Comment by SrinivasanTarget** [comment]
gulp nsp
[11:43:06] Using gulpfile ~/AppiumRepo/appium/gulpfile.js
[11:43:06] Starting 'nsp'...
[11:43:20] (+) No known vulnerabilities found
[11:43:20] Finished 'nsp' after 14 s

@imurchie It works fine after pointed to package.json file. Please let me know if this need to be ported to appium-gulp-plugins or its fine to be here?

**Comment by SrinivasanTarget** [comment]
Got it, nsp is not compatible with npm v2.Its already reported here,
https://github.com/nodesecurity/gulp-nsp/issues/24

**Comment by SrinivasanTarget** [comment]
@imurchie any updates?

**Comment by imurchie** [comment]
I think that yes, it ought to be in `appium-gulp-plugins`. It still doesn't work for me, though, even with updated node and npm. Weird.

**Comment by SrinivasanTarget** [comment]
Are you still getting package.json required error? @imurchie

**Comment by imurchie** [comment]
Yes. Works fine if I specify a `package.json`, but that doesn't fully specify what the packages are.

**Comment by SrinivasanTarget** [comment]
Thats enough is what i feel.I think 'nsp' will look into all the node modules which appium dependencies use too.

**Comment by imurchie** [comment]
What is enough?

I don't think parsing the `package.json` makes much sense if we are using `npm-shrinkwrap`, since the dependencies are locked down in the latter but loose in the former.

**Comment by SrinivasanTarget** [comment]
Using package.json is enough, 'nsp' by default will look into all the node modules used by appium dependencies too.

**Comment by imurchie** [comment]
But `npm shrinkwrap` locks the versions of the packages, while `package.json` uses semver. So `package.json` might specify "anything from 0.14.0 up to, but not including, 0.15.0" (`^0.14.0`) but it might be shrinkwrapped to "0.14.4".

**Comment by SrinivasanTarget** [comment]
Got it @imurchie will try to resolve the issue with npm shrinkwrap.

**Comment by SrinivasanTarget** [comment]
@imurchie It works only if we specify both shrinkwrap and package together.

**Comment by imurchie** [comment]
That works for me. Move it to `appium-gulp-plugins` and close this PR. Thanks!

**Comment by SrinivasanTarget** [comment]
Sure @imurchie Can i have this directly in gulp file of appium-gulp-plugin. https://github.com/appium/appium-gulp-plugins/blob/master/gulpfile.js#L30

**Comment by imurchie** [comment]
Hmm. Good question.

In that file is mostly babel/language stuff. I think other stuff should go toward the bottom of https://github.com/appium/appium-gulp-plugins/blob/master/lib/boilerplate.js

**Comment by SrinivasanTarget** [comment]
Closing this.

**Pull request closed without merging**
