### PR TITLE
Use latest instruments

### PR DESCRIPTION
**Pull request by imurchie**
Master isn't usable for iOS tests that update app preferences, without the latest from appium/instruments.

### CODE REVIEW

**Comment by jlipps** [comment]
has appium-instruments been published? usually a submodule ref and a package.json update go hand-in-hand.

**Comment by imurchie** [comment]
Hmm.

The repo says 1.7.3, which is what is in package.json. But the submodule is not on the same commit.

**Comment by jlipps** [comment]
ok (cc @Jonahss looks like this fell through the cracks)

**Comment by Jonahss** [comment]
ah

**Pull request merged**
