### PR TITLE
doc[cn]: the doc of drives.

### PR DESCRIPTION
**Pull request by youngfreeFJS**
## Proposed changes

I want to contribute to the Chinese version of the document page and help other people. 
This PR updates the driver documentation

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]
Could you create the same PR to https://github.com/appium/appium/tree/2.0 ?

**Comment by jlipps** [comment]
thanks @youngfreeFJS! you may also be interested in the conversation [here](https://github.com/appium/appium/issues/15566) about what we will do for docs in Appium 2.0.

**Comment by youngfreeFJS** [comment]
> Could you create the same PR to https://github.com/appium/appium/tree/2.0 ?

created at [here](https://github.com/appium/appium/pull/15568).
btw, the difference is adding a line of _Driver CLI_ at _docs/toc.js_ file.

**Comment by KazuCocoa** [comment]
thanks :)

**Comment by youngfreeFJS** [comment]
> thanks @youngfreeFJS! you may also be interested in the conversation [here](https://github.com/appium/appium/issues/15566) about what we will do for docs in Appium 2.0.

thanks @jlipps!  I am interested in this plan and want to contribute to it.

I have been following Appium 2.0 for a long time(😂 perhaps since at 2016 or 2017...) and looking forward to features like Appium plugins.

Waiting for your talks about _Appium 2.0_ in _APPIUM CONF_

**Comment by jlipps** [comment]
@youngfreeFJS \o/ i look forward to your collaboration, and thanks for your patience!

**Pull request merged**
