### PR TITLE
javascript: webdriverio findElement

### PR DESCRIPTION
**Pull request by Frederic-Zhou**
webdriverid V5

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dpgraham** [comment]
@ZetaChow I think the issue you were having is that you're using the `wd` library but ready the `webdriverio` example.

In the code snippet, it shows underneath `// wd example` the code snippet you should be using.

**Comment by ZetaChow** [comment]
> @ZetaChow I think the issue you were having is that you're using the `wd` library but ready the `webdriverio` example.
> 
> In the code snippet, it shows underneath `// wd example` the code snippet you should be using.

I use the version5 webdriverio lib 
I had read changelog , I found that the document is not updated, but the [simple-code](https://github.com/appium/appium/blob/master/sample-code/javascript-webdriverio/test/basic/ios-basic-interactions.test.js) was changed 

https://github.com/appium/appium/blob/master/sample-code/javascript-webdriverio/test/basic/ios-basic-interactions.test.js

and I found [ Get Start ](http://appium.io/docs/en/about-appium/getting-started/?lang=zh)example code have some error.

`const client = wdio.remote(opts);`
should add `await`
`const client = await wdio.remote(opts);`
otherwise, the next line will report an error.
`const elementId = await client.findElement("accessibility id","TextField1"); `

and add `async function`

**Comment by dpgraham** [comment]
I understand now. WebdriverIO v5 made breaking changes. I'll need to mention this to other Appium maintainers.

**Comment by ZetaChow** [comment]
I think it might be necessary to add an additional webdriverio version 5+ example to the api docs, and the mark the version number

**Comment by dpgraham** [comment]
Probably the best will be to write sample code that's compatible with 4 and 5 (if that's possible)

**Pull request closed without merging**
