### PR TITLE
docs: add ExternalDriver docstrings

### PR DESCRIPTION
**Pull request by jlipps**

### CODE REVIEW

**Comment by jlipps** [comment]
@boneskull is this the kind of thing you had in mind for me to do?

**Review by boneskull — APPROVED** [review]
yes

**Comment by boneskull** [comment]
It occurs to me that the methods return `X` but the API commands return `{"value": X}`.  Is there any command that breaks that assumption?  I can likely account for this.

**Comment by jlipps** [comment]
the command methods should return normal javascript values. a wrapper function converts those into actual protocol responses. no command method should know anything about how its response is wrapped up as a protocol response. it should only return the javascript value representing the result of its operation.

i.e., i don't think we want to annotate anything like `{value: 'foo'}` anywhere in our docs. clients always unwrap that into language-specific objects anyway

**Review by mykola-mokhnach — APPROVED** [review]
nicely done

**Comment by boneskull** [comment]
lgtm

**Pull request merged**
