### PR TITLE
docs: Change the Style Guide URL in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by soudai-s**
## Proposed changes

The link of CONTRIBUTING.md's Style Guide is dead, so fix that.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the CLA
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

### CODE REVIEW

**Comment by eglitise** [comment]
>The link of CONTRIBUTING.md's Style Guide is dead

Thanks, but the whole document hasn't been updated in 6 years and has several other dead links. I would say it is fully superseded by the document that you are linking to in this PR.
@mykola-mokhnach @KazuCocoa @jlipps maybe we can remove this file entirely? I can also try to use some of its contents to expand the current contributing docs.

**Comment by mykola-mokhnach** [comment]
> > The link of CONTRIBUTING.md's Style Guide is dead
> 
> Thanks, but the whole document hasn't been updated in 6 years and has several other dead links. I would say it is fully superseded by the document that you are linking to in this PR. @mykola-mokhnach @KazuCocoa @jlipps maybe we can remove this file entirely? I can also try to use some of its contents to expand the current contributing docs.

Ofc I support it if you'd like to improve the document. I would be happy to help with the review

**Comment by KazuCocoa** [comment]
Yea, it sounds good to me

**Comment by soudai-s** [comment]
OK, I will update docs after preparing that. Thank you so much for quick response.

**Pull request closed without merging**
