### PR TITLE
Fix grid register with Selenium 3 hubs

### PR DESCRIPTION
**Pull request by rgonalo**
## Proposed changes

Fix previous PR https://github.com/appium/appium/pull/7064
Selenium 3 has changed the format of grid config files, but not the configuration object that must be sent to the grid hub.
The Selenium 3 config file does not contain 'configuration' section, but request data must contain a 'configuration' section with all the properties.
Tested with Selenium 2.53.1 and Selenium 3.0.1.
## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- [X] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [X] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Review by jlipps — APPROVED** [review]

**Comment by jlipps** [comment]
thanks @rgonalo!

**Comment by SrinivasanTarget** [comment]
@rgonalo Were you able to register nodes to grid on both Selenium 3 and Selenium 2 with this changes?

**Comment by SrinivasanTarget** [comment]
@rgonalo Ok Got it. Our doc's are out of date here: https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/grid.md. Will update it.

**Pull request merged**
