### PR TITLE
Fixing perform touch with release action #5004

### PR DESCRIPTION
**Pull request by moizjv**
- Fixing defect due to popping of release action for touch perform
- Fixing associated unit test
- Fix for #5004 
- @jlipps and @imurchie please review

### CODE REVIEW

**Comment by imurchie** [comment]
Can we tweak any of the tests that touch this (other than the unit tests) so that they would actually catch the error that I introduced?

**Comment by moizjv** [comment]
@imurchie let me look in to it

**Comment by moizjv** [comment]
@imurchie done!

**Comment by imurchie** [comment]
This test distinguishes between the action with the `release` and without it?

**Comment by moizjv** [comment]
Yes [here](https://github.com/appium/android-apidemos/blob/master/src/io/appium/android/apis/view/SecureView.java#L129) it has alert only after ACTION_UP. it works fine

**Comment by moizjv** [comment]
Ohh may be i can keep old tests and these ones to test release because this ones might not test long press

**Comment by jlipps** [comment]
@moizjv are you wanting to add more work to this PR?

**Comment by moizjv** [comment]
@imurchie @jlipps done! added old tests back to check long click and new ones to test release

**Comment by jlipps** [comment]
:+1:  pending @imurchie OK

**Comment by imurchie** [comment]
lgtm!

**Pull request merged**
