### PR TITLE
chore: use commitlint

### LINKED ISSUE #17844: use commitlint
Might be worthwhile to adopt [commitlint](https://www.npmjs.com/package/@commitlint/cli).  I have it running on a couple of my projects and works well.

While we're in there, we should swap out `pre-commit` for `husky` given the former hasn't been published in six (6) years.

### PR DESCRIPTION
**Pull request by boneskull**
This adds [commitlint](https://npm.im/@commitlint/cli) to the project which validates commit messages against the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec via a preset.

Removed the [pre-commit](https://npm.im/pre-commit) package as it has not been updated in six (6) years; replaced with [husky](https://typicode.github.io/husky/) which is widely-used and full-featured.

Customized commitlint so that it will allow commit messages lines of arbitrary length; this is set to 100 by default, but is not in the specification.  If someone has a good reason that we _shouldn't_ disable that rule, please say something!

Closes #17844

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Review by jlipps — APPROVED** [review]
could we add a github action step that runs commitlint on the message of HEAD?

**Comment by boneskull** [comment]
@jlipps well.. what would we do about it if that check fails?

**Comment by boneskull** [comment]
okay I think by `HEAD` you mean "in a PR" because once it gets to `master`...

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* master
  * **PR #17857** <a href="https://app.graphite.dev/github/pr/appium/appium/17857" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium/17857?utm_source=stack-comment).

**Comment by boneskull** [comment]
@jlipps See 7373125

**Comment by boneskull** [comment]
hm.

**Review by jlipps — APPROVED** [review]
yeah nice! i like it. we can always still choose to squash and rebase if we want.

**Pull request merged**
