### PR TITLE
Update appium-instruments

### PR DESCRIPTION
**Pull request by romainlouvet**

### CODE REVIEW

**Comment by sharky101** [comment]
+ 1

**Comment by sharky101** [comment]
Version 1.4.2 appium-xcode got bumped to 2.0.5. appium-instruments was missed, this also needed to be bumped to 2.0.4 which has appium-xcode 2.0.5 as a dependency.

**Comment by sebv** [comment]
You can use 1.4.3-beta until fix is released.

**Comment by xudafeng** [comment]
+1

**Comment by sharky101** [comment]
@sebv thanks. 1.4.3-beta works fine in OSX.

**Comment by jlipps** [comment]
1.4.3 now released

**Pull request closed without merging**
