### PR TITLE
build(lodash): force resolution to 4.17.11 minimum

### PR DESCRIPTION
**Pull request by bcabanes**
## Proposed changes

There is currently an issue in the resolution of the `lodash` library for packages depending of this package. Any version of `lodash` before the `4.17.11` cause a _moderate_ warning from NPM Audit.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

The change made, forces the `lodash` resolution to the `4.17.11` version to prevent
dependency warnings due to prototype pollution from lower `lodash`
versions.

### CODE REVIEW

**Review by dpgraham — APPROVED** [review]
Thank you!

**Review by imurchie — APPROVED** [review]
Thanks!

The warning will still be there, since [appium-sbd](https://github.com/Samsung/appium-sdb) still depends on `lodash@3.10.1`:
```
├─┬ appium-tizen-driver@1.1.1-beta.3
│ ├─┬ appium-sdb@1.0.0-beta
│ │ └── lodash@3.10.1
│ └── lodash@4.17.11  deduped
```

**Comment by bcabanes** [comment]
@imurchie Hey! is it possible to cut a new release of `appium-sdb`?
The repository is using the latest version of `lodash` on master and the code has been updated too:
https://github.com/Samsung/appium-sdb/commit/aee548cb79d8b54c9ca465bc6e51e307ac23eb13

https://github.com/Samsung/appium-sdb/blob/master/package.json#L44

**Comment by imurchie** [comment]
Unfortunately, I do not have access to that package. 

However, Appium does not load drivers until they are needed, so if you aren't using the Tizen driver then the low lodash won't be used. The warning will still be printed there when installing, though.

**Pull request merged**
