### PR TITLE
1.3.7-beta

### PR DESCRIPTION
**Pull request by 0x1mason**
Creating a hot fix branch including the `Fixed fail to find xcode` and `fix failure to remap session id in proxied responses`

### CODE REVIEW

**Comment by 0x1mason** [comment]
@bootstraponline @paymand @jlipps This is my first attempt at using trunk-based dev.  I wrote something up that I hope to share this week that tries to outline procedures.  Anyway, so here's the version change for a new branch I'm creating.  Next time, we can start properly with a 1.4 branch, but since this needs to get out asap, I'm going to do a 1.3.7-branch for this small hotfix release and pull in:

Fixed fail to find xcode: 54f9b3af226374329fbf0bec903de6fbad4550a6
Wrong helpers: ffb9a5af7603d17b7b90ff5e4e690fe33f357540
Move Xcode tests to iOS functional tests: 0721bd949a0d986a33494025c550343562824c08
fix failure to remap session id in proxied responses: e194212e1aedf47e3338c5025f163313976f14a1
Fix link to appium-support.util: ab8f6e2f2b85dea3cc2ff0f05ab16a45dbdf5cd4

**Comment by bootstraponline** [comment]
Sounds good to me. :+1:

**Comment by jlipps** [comment]
:+1:

**Comment by paymand** [comment]
:+1:

**Pull request merged**
