### PR TITLE
Doc tweaks

### LINKED ISSUE #6243: Document - update JSON Wire Protocol link
## The problem

Mobile JSON Wire Protocol links are still pointing to the decommissioned code.google.com URL.

## Details

The current document like https://github.com/appium/appium/blob/master/docs/en/about-appium/intro.md or https://github.com/appium/appium/blob/master/docs/en/about-appium/appium-clients.md are still pointing to `code.google.com` for JSON Wire Protocol reference, which is resolved to a deprecated link https://github.com/seleniumhq/selenium-google-code-issue-archive now.

When people want to add their own binding libraries, it will become very confusing. It would be much better to update all these links to the official link of JSON Wire Protocol, which I couldn't find at the moment.

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
## Proposed changes

Doc tweaks that updates broken links for JSON Wire Protocol.This fixes #6243 
## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by moizjv** [comment]
Can one of the admins verify this patch?

**Comment by imurchie** [comment]
That link is obsolete. Should we not use `https://w3c.github.io/webdriver/webdriver-spec.html`?

**Comment by SrinivasanTarget** [comment]
I just noticed it.Thanks will update @imurchie

**Comment by SrinivasanTarget** [comment]
@imurchie Updated now.

**Comment by imurchie** [comment]
Excellent! Thanks!

**Pull request merged**
