### PR TITLE
docs(appium): update JS quickstart example

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

I recognised that the quickstart example uses an outdated WebdriverIO version. This patch updates that.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

I hope I will get around to create some mobile testing docs where we could link the Appium users to.

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Comment by christian-bromann** [comment]
@KazuCocoa can you trigger a new deploy of the website please?

**Comment by KazuCocoa** [comment]
@jlipps What is current docs push flow in this repository?

**Comment by christian-bromann** [comment]
https://github.com/appium/appium/actions/workflows/deploy.yml ?

**Comment by jlipps** [comment]
Hmm I'm not sure we have one yet. Let me run a docs deploy manually for now

**Comment by jlipps** [comment]
OK, docs have been deployed. For future reference I just ran `npm run publish:docs` in the `packages/appium` directory.

**Comment by christian-bromann** [comment]
Thanks Jonathan!

**Comment by KazuCocoa** [comment]
nice, will create a GA action like xcuitest driver so that it will work via GA task

**Pull request merged**
