### PR TITLE
chore(base-driver): remove non-W3C route which are already in W3C

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Proposed changes

We'd eventually remove non-W3C and not used by Appium commands for 2.0
Part of https://github.com/appium/appium/issues/15729

This PR removes duplicated routes with W3C and non-W3C.
We already accept only W3C protocol, so non-W3C routes but they are already in W3C can remove safely, I think.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by jlipps — APPROVED** [review]

**Comment by KazuCocoa** [comment]
mm, current master raised the below error on CI

```
  48 passing (1m)
  1 pending
  2 failing

  1) FakePlugin
       cli args handling for plugin args
         should recieve user cli args for plugin if passed in:
     TypeError: Cannot read properties of null (reading 'should')
      at Context.<anonymous> (test/plugin-e2e-specs.js:172:20)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  2) FakePlugin
       cli args handling for empty plugin args
         should not recieve user cli args for plugin if none were passed in:
     TypeError: Cannot read properties of null (reading 'should')
      at Context.<anonymous> (test/plugin-e2e-specs.js:195:20)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jlipps** [comment]
I believe I fixed that yesterday. Is it still happening?

**Comment by jlipps** [comment]
Or, I think it is just fixed recently with the driver-args PR merge actually.

**Comment by KazuCocoa** [comment]
oh, yea, latest 2.0 got green https://github.com/appium/appium/commits/2.0

**Pull request merged**
