### PR TITLE
update grid.md

### PR DESCRIPTION
**Pull request by tobecrazy**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by jlipps** [comment]
@tobecrazy did you intend to open this PR? there are some odd things about it and I want to make sure it's not an accident.

**Comment by tobecrazy** [comment]
@jlipps  I think so, I only translate docs to Chinese .

**Comment by jlipps** [comment]
@lihuazhang are you involved with this effort? or are you able to review this and see whether these updates make sense? if so we can squash and merge.

**Comment by mingyuan-xia** [comment]
Hi @jlipps I am following up to complete these three PRs from the Chinese community. 
https://github.com/appium/appium/pull/7938
https://github.com/appium/appium/pull/7939
https://github.com/appium/appium/pull/7819

7819 (this one) is strictly a subset of 7938, you can discard it.
The remaining two are translation patches, touching only files under `docs/cn/`.
7939 goes before 7938.
7939 is the initial draft and adds some translated doc files to `docs/cn/`.
7938 renames some of those files and fixes typos.
All changes stay under `docs/cn/` and should be fine.

Please continue to discard 7819, merge 7939 and finally merge 7938.
Sorry for the mess this time and I will coordinate the joint efforts of `testerhome:master` to get organized and timely PRs in the future.

Let me know if anything else.

**Comment by jlipps** [comment]
@mingyuan-xia thanks and that sounds good! However the PR to merge first (#7939) has conflicts and can't be merged. Can someone fix the conflicts so I can merge it?

**Comment by jlipps** [comment]
(FWIW #7938 can be merged at the moment if that is what should happen)

**Pull request closed without merging**
