### PR TITLE
updating setting up current location for iOS 8.1 & 8.2

### PR DESCRIPTION
**Pull request by aleks2a**

### CODE REVIEW

**Comment by jlipps** [comment]
@imurchie can you review? i thought we already merged something to this effect...?

**Comment by aleks2a** [comment]
it was submitted by my colleague, and was merged to 1.3.6-beta, but never to 1.3.6

**Comment by jlipps** [comment]
@0x1mason can you comment on this? was it not merged to master?

**Comment by 0x1mason** [comment]
No, I can see it in 1.3.6-beta, but not in 1.3.6-beta2. Not sure how that happened, but I'm obviously responsible. I apologize.  The good news is the new branch model makes this type of mistake impossible.

**Comment by jlipps** [comment]
ok; we might want to be on guard to see if we want to cherry-pick this into a 1.3.8 patch release

**Comment by 0x1mason** [comment]
Yes, I think we might want to do that.

**Pull request merged**
