### PR TITLE
Migration doc xpath

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Proposed changes

Add recommendations regarding xpath usage in XCUITest mode

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Review by imurchie — APPROVED** [review]
Good advice, to me. Thanks!

**Comment by jlipps** [comment]
Beautiful, thanks @mykola-mokhnach

**Pull request merged**
