### PR TITLE
Don't url encode cookie value

### PR DESCRIPTION
**Pull request by SBoudrias**
This change is to ensure we stay consistent with other selenium driver
implementation.

This is a follow PR on #4727

### CODE REVIEW

**Comment by SBoudrias** [comment]
Hey, any feedback on this change? We can also discuss it further on the issue tracker.

**Comment by jlipps** [comment]
hi @SBoudrias i'm not sure what's at stake here. can @sebv chime in please?

**Comment by SBoudrias** [comment]
On my side, the issue is that we'll run test in both desktop browsers and mobile browsers. So having a consistent behavior about how cookies are handled in both selenium drivers is very important.

**Comment by jlipps** [comment]
sure i believe you, just wondering why we did this in the first place

**Comment by SBoudrias** [comment]
It seems to me jquery.cookie encode the cookies, so the code encoding them have just been kept when porting the module to appium https://github.com/carhartl/jquery-cookie/blob/master/src/jquery.cookie.js#L23-L25

**Comment by jlipps** [comment]
ok, merged. thank you!

**Comment by SBoudrias** [comment]
Awesome, thanks!

**Pull request merged**
