### PR TITLE
fix: --suppress-adb-kill-server as store_true

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Proposed changes

`--suppress-adb-kill-server` should be true or false like `--log-timestamp`, same as Appium 1.20.2 and before.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by KazuCocoa** [comment]
ping @jlipps

**Review by jlipps — APPROVED** [review]

**Comment by jlipps** [comment]
i guess this was removed in the 2.0 branch so we don't need a PR there?

**Comment by KazuCocoa** [comment]
oh, then, missed removing it?

```
usage: appium server [-h] [-ah APPIUMHOME] [--log-filters] [--shell] [--plugins PLUGINS] [--allow-cors] [--reboot REBOOT] [-a ADDRESS] [-p PORT]
                     [-pa BASEPATH] [-ka KEEPALIVETIMEOUT] [-ca CALLBACKADDRESS] [-cp CALLBACKPORT] [--session-override] [-g LOGFILE]
                     [--log-level {info,info:debug,info:info,info:warn,info:error,warn,warn:debug,warn:info,warn:warn,warn:error,error,error:debug,error:info,error:warn,error:error,debug,debug:debug,debug:info,debug:warn,debug:error}]
                     [--log-timestamp] [--local-timezone] [--log-no-colors] [-G WEBHOOK] [--nodeconfig NODECONFIG]
                     [--chromedriver-port CHROMEDRIVERPORT] [--chromedriver-executable CHROMEDRIVEREXECUTABLE] [--show-config] [--no-perms-check]
                     [--strict-caps] [--tmp TMPDIR] [--trace-dir TRACEDIR] [--debug-log-spacing] [--suppress-adb-kill-server SUPPRESSKILLSERVER]
                     [--long-stacktrace] [--webkit-debug-proxy-port WEBKITDEBUGPROXYPORT] [--webdriveragent-port WDALOCALPORT]
                     [-dc DEFAULTCAPABILITIES] [--relaxed-security] [--allow-insecure ALLOWINSECURE] [--deny-insecure DENYINSECURE]
```

**Comment by jlipps** [comment]
oh i didn't realize this was being merged into 2.0 :-) yeah with 2.0 the goal was to remove all driver-specific flags and have them handled either as capabilities only (via default capabilities if necessary) or via custom driver flags which the drivers expose (and not the main server)

**Comment by KazuCocoa** [comment]
ah, gotcha

**Comment by bb-cn-himanshu** [comment]
Hi @jlipps 
Can you please help me understand work-around for above flag
is this now being handled via capabilities or custom driver flags? can you please point me to the correct replacement for above mentioned flag.

I am getting error with below mentioned flags
```
Unrecognized arguments: --bootstrap-port 50358 --suppress-adb-kill-server
```

**Comment by jlipps** [comment]
yes, these are caps now. `bootstrapPort` no longer exists because that was for the old android driver. you can find info on suppress kill server in the [uiauto2 driver docs](https://github.com/appium/appium-uiautomator2-driver). (hint: it's `appium:suppressKillServer`)

**Comment by bb-cn-himanshu** [comment]
Thanks alot @jlipps, big help

**Pull request merged**
