### PR TITLE
fix(images-plugin): Handle the case when error message is undefined

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Proposed changes

Addresses https://github.com/appium/appium/issues/17753

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Review by boneskull — COMMENTED** [review]
Do _we_ throw these exceptions, or are they coming out of third-party code? 

If we throw them, we should probably just subclass `Error` and do an `instanceof` check instead of a regex on the `message`...

**Comment by mykola-mokhnach** [comment]
> Do _we_ throw these exceptions, or are they coming out of third-party code?
> 
> If we throw them, we should probably just subclass `Error` and do an `instanceof` check instead of a regex on the `message`...

These exceptions are thrown by other package (opencv). I don't know how to properly orchestrate versions bump there in order to implement such strategy. Also I remember there were issues while using instanceof for error classes of these are being imported from other packages

**Comment by boneskull** [comment]
@mykola-mokhnach 

> Also I remember there were issues while using instanceof for error classes of these are being imported from other packages

What are you referring to here?

I mean, the type or shape of a given `Error` should be considered part of its public API, while contents the error message itself is not necessarily.  _In general_--and considering the policy/history of any given dependency--to distinguish exceptions, I'd rather leverage basically _any_ other bit of information.  

In other words, checking a `message` to determine what kind of `Error` you have may be more risky (in terms of unexpected breakage) than other strategies.  Again, it kind of depends on the dependency and how it's maintained.  

I'm not asking you to change anything necessarily, but--assuming we have not already done so--we should do our due diligence on the project (`opencv`?) & its API and see if there's anything else we should be using to distinguish these errors.

**Comment by mykola-mokhnach** [comment]
The opencv package is in the same monorepo. 

What I'm referring to was also the reason of having isErrorType function in https://github.com/appium/appium/blob/c43acc23ee80d461747c1912cdcfb136280001a0/packages/base-driver/lib/protocol/errors.js
@jlipps probably has more background there as this code already existed after I joined.

**Comment by mykola-mokhnach** [comment]
Generally I agree that checking the error type makes more sense over checking its message

**Comment by boneskull** [comment]
Better than `instanceof` would be a `code` prop on the error which is some constant string we can just prepare, like node does

**Comment by jlipps** [comment]
The problem is that `instanceof` checks don't work when the error class imported by the checker is from a different version of the npm package than the error class imported by the thrower.

If we're sure that the error class is imported in the same place by checker and thrower, then the `instanceof` check will work. This was not a guarantee in earlier versions of appium. As you can imagine, this was a weird bug to track down when it first popped up.

**Review by jlipps — APPROVED** [review]

**Comment by jlipps** [comment]
> Better than instanceof would be a code prop on the error which is some constant string we can just compare, like node does

That could be a good way to reimplement `isErrorType`

**Pull request merged**
