### PR TITLE
Remove invalid word from docs

### PR DESCRIPTION
**Pull request by WillBrock**
## Proposed changes

Removing the word `fuller` from the docs since it's not a correct english word.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by imurchie** [comment]
> it's not a correct english word
This is untrue, though.

**Comment by WillBrock** [comment]
Sorry, it's a correct word but is used incorrectly in this case.

**Comment by imurchie** [comment]
Even that is not correct (there is a description on the page; there is a _fuller_ (as the comparative form of _full_) description on another page; there is not, for better or for worse, a _fullest_ description on any other page).

I'm ok with the change as it stands, though.

**Comment by WillBrock** [comment]
You're right. I guess I've never seen it used this way.

**Review by jlipps — APPROVED** [review]

**Comment by jlipps** [comment]
Yeah, `fuller` is OK, but I'm also fine with `more comprehensive`, which is a ... more comprehensive ... way of saying the same thing.

**Pull request merged**
