### PR TITLE
Move Xcode tests to iOS functional tests

### PR DESCRIPTION
**Pull request by 0x1mason**

### CODE REVIEW

**Comment by 0x1mason** [comment]
@sebv @paymand

**Comment by paymand** [comment]
:+1:

**Comment by paymand** [comment]
> Added logic to skip Xcode tests on non-OSX machines

What logic have you added here? To me it looks like you just moved the test from unit tests to iOS functests (which is the correct thing to do, but I guess the commit message should be updated).

**Comment by 0x1mason** [comment]
@paymand Good pt about the commit msg.  Will update.

**Comment by 0x1mason** [comment]
@paymand changed to "Fix for commit hook failure on non-OSX machines: moved Xcode path tests to functional tests"

**Comment by paymand** [comment]
Very loooooong, but much better ;)

**Comment by 0x1mason** [comment]
hehe :+1:

**Comment by paymand** [comment]
is what I think was enough: ^

**Pull request merged**
