### PR TITLE
chore(base-driver): start to document BaseDriver types for TS users

### PR DESCRIPTION
**Pull request by jlipps**
I decided to write a typescript plugin to see what we would need in terms of type definitions, so here's my first stab.

### CODE REVIEW

**Comment by jlipps** [comment]
going through this code is also helping me realize how much of an opportunity for some nice refactoring there is here :-)

**Review by KazuCocoa — COMMENTED** [review]
nice 👍
Will this pr include TODO comment as well?

**Comment by jlipps** [comment]
I think I will actually add the commands before merging

**Comment by jlipps** [comment]
OK, I've added the rest of the things I found in BaseDriver. There are a few types that could probably be expanded later on, but this at the very list will be quite helpful for driver developers.

**Review by KazuCocoa — APPROVED** [review]

**Pull request merged**
