### PR TITLE
fix(appium): Load plugins in the same order that was used for the CLI command

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Proposed changes

Addresses https://discuss.appium.io/t/how-can-you-control-order-of-how-cmds-are-handled-by-appium-when-shared-by-multiple-plugins/40769

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Review by KazuCocoa — COMMENTED** [review]
it makes sense to keep the order

**Review by KazuCocoa — APPROVED** [review]

**Comment by kandji-joel** [comment]
@mykola-mokhnach @KazuCocoa what is your release cadence? I'm wondering when I should expected an updated version of Appium that includes these changes

**Comment by mykola-mokhnach** [comment]
cc @jlipps ^

**Comment by jlipps** [comment]
just published Appium 2.2.2 with this change included.

**Pull request merged**
