### PR TITLE
add WinAppDriver beta under the Windows platform

### PR DESCRIPTION
**Pull request by jlipps**
## Proposed changes

Give users access to Windows Desktop app automation
## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules
## Further comments

Documentation to come. cc @yodurr @imurchie

### CODE REVIEW

**Comment by imurchie** [comment]
Nice!

Two thoughts:

0. The build is failing because of this line: https://github.com/appium/appium-windows-driver/blob/master/lib/installer.js#L11 which needs a default value or else we need to set an environment variable.

0. I think there needs to be a conditional in the `install-npm.js` script, to skip everything if it is a non-Windows system. We **know** that it will fail, so why allow it to try? It also clears up a lot of waiting around for the dependencies to get up to speed.

**Comment by jlipps** [comment]
good points, will address

**Comment by jlipps** [comment]
ok changes made in windows driver, let's see if this helps

**Comment by jlipps** [comment]
@imurchie travis passed this time at least

**Comment by imurchie** [comment]
This fails to install for me (on OSX 10.11.5):


```
268187 verbose stack Error: appium-windows-driver@0.1.2 install: `node install-npm.js`
268187 verbose stack Exit status 1
268187 verbose stack     at EventEmitter.<anonymous> (/Users/isaac/.nvm/versions/node/v0.12.14/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
268187 verbose stack     at EventEmitter.emit (events.js:110:17)
268187 verbose stack     at ChildProcess.<anonymous> (/Users/isaac/.nvm/versions/node/v0.12.14/lib/node_modules/npm/lib/utils/spawn.js:24:14)
268187 verbose stack     at ChildProcess.emit (events.js:110:17)
268187 verbose stack     at maybeClose (child_process.js:1019:16)
268187 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
268188 verbose pkgid appium-windows-driver@0.1.2
268189 verbose cwd /Users/isaac/code/appium
268190 error Darwin 15.5.0
268191 error argv "/Users/isaac/.nvm/versions/node/v0.12.14/bin/node" "/Users/isaac/.nvm/versions/node/v0.12.14/bin/npm" "install"
268192 error node v0.12.14
268193 error npm  v2.15.1
268194 error code ELIFECYCLE
268195 error appium-windows-driver@0.1.2 install: `node install-npm.js`
268195 error Exit status 1
268196 error Failed at the appium-windows-driver@0.1.2 install script 'node install-npm.js'.
268196 error This is most likely a problem with the appium-windows-driver package,
268196 error not with npm itself.
268196 error Tell the author that this fails on your system:
268196 error     node install-npm.js
268196 error You can get information on how to open an issue for this project with:
268196 error     npm bugs appium-windows-driver
268196 error Or if that isn't available, you can get their info via:
268196 error
268196 error     npm owner ls appium-windows-driver
268196 error There is likely additional logging output above.
268197 verbose exit [ 1, true ]
268198 verbose unbuild node_modules/appium-windows-driver
268199 info preuninstall appium-windows-driver@0.1.2
268200 info uninstall appium-windows-driver@0.1.2
268201 verbose unbuild rmStuff appium-windows-driver@0.1.2 from /Users/isaac/code/appium/node_modules
268202 info postuninstall appium-windows-driver@0.1.2
268203 silly gentlyRm /Users/isaac/code/appium/node_modules/appium-windows-driver is being purged from base /Users/isaac/code/appium
268204 verbose gentlyRm don't care about contents; nuking /Users/isaac/code/appium/node_modules/appium-windows-driver
```

**Comment by jlipps** [comment]
odd, it worked for me; what version of node are you using?

**Comment by yodurr** [comment]
Looks like node v0.12.14
Shouldn't the install script do nothing on Mac?

**Comment by jlipps** [comment]
yeah i think it's node 0.12 issue. we're requiring >= 4 moving forward so this shouldn't be a problem. @imurchie is this mergeable now then?

**Comment by imurchie** [comment]
I will merge the node requirement and then this should be good to go!

**Comment by imurchie** [comment]
All seems good to me! Merging.

**Pull request merged**
