### PR TITLE
docs: reflect sponsors, WebdriverIO and TestingBot

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Proposed changes

Add WebdriverIO and TestingBot from recent opencollevtive activities

They are listed in a list, so I removed "Become a xxx" from list style. I also added a note about the order was alphabetical one basis to clarify the order reason

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the CLA
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by jlipps — APPROVED** [review]

**Comment by eglitise** [comment]
Can we add logos? Presenting sponsors in a plain list isn't exactly appealing.

**Comment by KazuCocoa** [comment]
Maybe then we should request them to share logos. I'm not sure if it could but we may be able to ask sponsors to give a specific format's logo then? Or maybe it would be nice to embedded opencollective's sponsor pages if possible. (We need to take a look if these could)

**Comment by eglitise** [comment]
Isn't it enough to just grab the logo from their website? At least that's how the logos for the Inspector's cloud providers were gathered. As an example, for WDIO, they have ESLint as one of their sponsors, and they simply link to ESLint's website for the logo image.

**Comment by KazuCocoa** [comment]
Perhaps it could (i like to add icons itself, btw). This PR just followed the existing one, so we could decide and create a separate PR later. Then maybe we also could ask existing sponsors to use their logo icons from website etc and update opencollevtive description as well

**Comment by KazuCocoa** [comment]
Created -> https://github.com/appium/appium/issues/20167

**Comment by KazuCocoa** [comment]
-> https://github.com/appium/appium/pull/20170

**Pull request closed without merging**
