### PR TITLE
Update ChangeLog for 1.6.4 beta release

### PR DESCRIPTION
**Pull request by imurchie**
## Proposed changes

Add CHANGELOG in preparation for 1.6.4 beta release.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dpgraham** [comment]
lgtm

**Comment by jlipps** [comment]
LGTM! i feel like there are potentially more changes hidden in the commit logs for the subrepos though

**Comment by imurchie** [comment]
I went through everything and this was all that seemed relevant (excluding internal changes, and documentation).

**Comment by jlipps** [comment]
👍

**Pull request merged**
