### PR TITLE
Added solution for Instruments crashes on devices

### PR DESCRIPTION
**Pull request by aelr**
## Proposed changes

No code - only a tip on the Troubleshooting doc.

I spent the last 4 months wondering why Appium would stop working (due to Instruments crashes) in a CI system.  Occasionally, it would start working again, but the cause was not clear.  Finally, after updating all connected devices to 9.3.2 last Friday, it stopped working completely. I finally [found a solution](https://discuss.appium.io/t/ios-inspector-not-working-in-new-9-3-2-when-it-worked-previously/10340/6) that worked.  With how many other posts I've seen about this, it seemed like it warranted a spot on the troubleshooting doc.
## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

None.
## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

Do I need to sign the CLA for this?
- [ ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
### Reviewers:

None.

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by imurchie** [comment]
Thanks! This is very useful.

**Comment by jlipps** [comment]
thank you @aelr !

**Pull request merged**
