### PR TITLE
chore: use appium2 version of base driver

### PR DESCRIPTION
**Pull request by jlipps**
Want to pull in the breaking change regarding default base path, for the 2.0 branch.

### CODE REVIEW

**Comment by jlipps** [comment]
(this should hopefully fix CI)

**Comment by mykola-mokhnach** [comment]
> (this should hopefully fix CI)

Unfortunately the CI is still not passing :(

**Comment by jlipps** [comment]
hmm, this is many new errors. i'll have to look into it.

**Comment by jlipps** [comment]
ok, turns out i had to update a lot of test code. now it's working!

**Review by mykola-mokhnach — APPROVED** [review]

**Pull request merged**
