### PR TITLE
startRecordingScreen() not available on Javascript

### PR DESCRIPTION
**Pull request by joshuapinter**
When trying to call this you get `startRecordingScreen is not a function`.

The docs are misleading and they point to the erroneous line in the commands file. I'm not sure why it's not supported on Javascript but it should at least be better documented that it isn't.

## Proposed changes

Docs change.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jlipps** [comment]
Seems to be supported in wdio still: https://webdriver.io/docs/api/appium#startrecordingscreen

**Comment by jlipps** [comment]
If you get an error when using that client library, I would submit an issue to WDIO instead.

**Comment by joshuapinter** [comment]
Yeah, it's confusing to know where the core issue lies. I found some corroboration with Bitrise on their article for recording your UI tests as well: 

image

https://devcenter.bitrise.io/tips-and-tricks/screen-recording-your-ui-tests-with-appium/

I'll post an issue there and link it back to here but we're on the latest versions of everything and it just doesn't appear to be supported. And these docs don't point to anywhere meaningful like they do for something like `saveScreenshot`, etc.

**Comment by joshuapinter** [comment]
I dug a little more into this. First off, we are using `wd` and not `wdio`. Looking at `wdio`'s docs, I think you're right, they definitely seem to support this. But `wd` definitely does not.

So, I'll update this commit to keep the `wdio` references and show that `wd` does not support it. 

I really wish they did because the migration from `wd` to `wdio` is not insignificant but I would love to be able to use `startRecordingScreen` without rolling our own solution.

**Comment by jlipps** [comment]
Unfortunately WD is no longer maintained so sooner or later you'll probably want to move to WDIO anyway.

**Comment by joshuapinter** [comment]
Thanks for the heads up, @jlipps. That's what I was gleaning as well. I'll put it on The List. :)

**Review by mykola-mokhnach — APPROVED** [review]

**Pull request merged**
