### PR TITLE
Update intro.md

### PR DESCRIPTION
**Pull request by ghost**
Include a mention to TestingBot's Appium grid which allows for testing mobile apps on both sim/emu and physical devices.
We'd greatly appreciate it if you could add our link to the document.

## Proposed changes

This is a modification to the intro.md file to include a link to TestingBot

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jlipps** [comment]
Thanks for this patch. We should probably decide whether to accept this patch or remove mention of all cloud company names. We certainly don't want this sentence to contain a list of all Appium cloud providers. What do you think @mykola-mokhnach @boneskull @KazuCocoa?

**Comment by boneskull** [comment]
a list of providers may make sense for an "awesome-appium" repo that we can link to somewhere

**Comment by jlipps** [comment]
it looks like @SrinivasanTarget already maintains one: https://github.com/SrinivasanTarget/awesome-appium

**Comment by KazuCocoa** [comment]
Agree with that https://github.com/appium/appium/pull/15768#issuecomment-902838702
It would be nice to move such list in another page or move out of appium.io like the awesome-appium repo so that anyone can update them.

**Comment by boneskull** [comment]
@testingbot Please open a PR to [awesome-appium](/srinivasantarget/awesome-appium)

**Pull request closed without merging**
