### PR TITLE
prep for adding command documentation

### PR DESCRIPTION
**Pull request by boneskull**
This PR contains a bunch of changesets--mostly involving types--in preparation for creating a TypeDoc plugin which automatically documents driver/plugin/builtin commands (API endpoints).

The implementation of `typedoc-plugin-appium` will be linked below.

### CODE REVIEW

**Comment by boneskull** [comment]
I can probably try harder to sort out the changesets.  Some of them contain reverts of previous ones...

**Comment by boneskull** [comment]
This started as a fork of the `jlipps/command-docs` branch

**Comment by boneskull** [comment]
alright, I broke something here, so gotta fix that.  this is why we write tests!

**Comment by boneskull** [comment]
OK, this happened because of the fake-driver-mixin thing.  It looks like a more robust method of deleting sessions is needed in `AppiumDriver`

**Comment by boneskull** [comment]
The problem was that `caps` was `undefined` when the `driverData` getter was called by `deleteSession` (and _why_ this is being accessed here is still anybody's guess).  I've modified the `BaseDriverCore` constructor to set `this.caps = {}`.  Unclear why TS wasn't raising a stink about this property leaving the constructor w/o getting defined; probably has something to do with the mixins obscuring the prototype chain...

**Review by jlipps — APPROVED** [review]
not sure why CI is unhappy but all this type groundwork seems ok

**Comment by boneskull** [comment]
yeah trying to reproduce that failure locally.  wouldn't be surprised if it's a race condition

**Pull request merged**
