### PR TITLE
docs: add notice in the changelog

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Proposed changes

This repository's changelog is no longer maintained. So I think this branch's changelog should have only pointers for each place, 1.x is for 1.x branch and 2.0 based drivers are each repository (ecosystem page to keep them being maintained)

(Part of https://github.com/appium/appium/issues/18607)

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by eglitise** [comment]
If I may... I fully agree with not tracking driver changes anymore, but would it not be worth keeping a changelog for the root appium module? The releases section also tracks other modules, so finding the overall changes would be a lot easier this way.

**Review by jlipps — APPROVED** [review]

**Comment by jlipps** [comment]
@eglitise each package now has its own CHANGELOG.md in the package directory. We could keep a high-level CHANGELOG which simply redirects people to the Appium package CHANGELOG.md instead.

**Comment by eglitise** [comment]
@jlipps thanks, I was unaware of this, the individual changelogs make it very easy to track changes.
I agree on linking to the Appium package changelog from the top-level changelog; it could also be changed into an aggregate page with links to all the modules' changelogs, plus the existing links to ecosystem and 1.x.

**Comment by jlipps** [comment]
Yeah an aggregate page with links makes sense!

**Pull request merged**
