### PR TITLE
Support Flutter driver

### PR DESCRIPTION
**Pull request by truongsinh**
## Proposed changes

As discussed in https://github.com/appium/appium/issues/12919#issuecomment-513566934, we need to declare package name and class name for Flutter Driver.
## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

In the long run however, I believe this part of code should be refactored so that arbitrary driver can run without code change from `appium` core. Security risk should be minimal because that package must be installed beforehand anyway.

### CODE REVIEW

**Comment by truongsinh** [comment]
Please help to validate whether this need accompanied unit test.

**Comment by truongsinh** [comment]
cc @KazuCocoa @jlipps

**Comment by jlipps** [comment]
The code here looks good, we should have a look at the actual flutter driver code and evaluate it before formally making it a built-in Appium driver, though.

**Comment by KazuCocoa** [comment]
You should specify your npm package following https://github.com/appium/appium/pull/12945/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L45-L57
Then, you can resolve the dependencies in this branch

**Comment by KazuCocoa** [comment]
and requires it like https://github.com/appium/appium/pull/10938/files

**Comment by confiks** [comment]
Is there anything holding back the merge of this PR?

**Pull request merged**
