### PR TITLE
CI Improvements

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
## Proposed changes

1)Migrating from legacy to container-based infrastructure
 https://docs.travis-ci.com/user/migrating-from-legacy
2)Execution on stable (latest) version of node
## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules
## Further comments

https://docs.travis-ci.com/user/migrating-from-legacy#Why-migrate-to-container-based-infrastructure%3F

### CODE REVIEW

**Comment by moizjv** [comment]
Can one of the admins verify this patch?

**Comment by imurchie** [comment]
Looks good to me.

**Comment by bootstraponline** [comment]
:+1:

**Comment by SrinivasanTarget** [comment]
Thanks @imurchie @bootstraponline

**Pull request merged**
