### PR TITLE
newCommandTimeout is not set when autLaunch is set to false

### PR DESCRIPTION
**Pull request by yaphatak**
newCommandTimeout is not set when autLaunch is set to false.

### CODE REVIEW

**Comment by jlipps** [comment]
This probably needs to be integrated into Appium 1.5 instead (where I don't think we will have the autoLaunch anyway), cc @imurchie @sebv

**Comment by imsardine** [comment]
Currently a workaround for this issue is to explicitly specify default command timeout (`--command-timeout`) in the command line.

BTW, @jlipps I'm not sure what you mean by "I don't think we will have the autoLaunch anyway", and I'm afraid of the removal of the cap. We do need this cap to support "multiple test cases in a session", where each test case opens the app (setup) and closes it later (teardown).

**Comment by jlipps** [comment]
@sebv had a good proposal of how to provide the equivalent of autoLaunch without appium having to actually implement

**Comment by imurchie** [comment]
Unfortunately, in the shuffle of Appium 1.5, this PR got very messed up. If the problem that it was meant to solve persists in 1.5, can you either (a) open an issue explaining the problem and the solution, or (b) open a new PR?

We apologize for the mess up. :(

**Pull request closed without merging**
