### PR TITLE
fix: add 'webSocketUrl' as standard cap for bidi support

### PR DESCRIPTION
**Pull request by jlipps**
cc @christian-bromann this should be added to the w3c spec as a standard cap once bidi is ratified, yes? i think we'll need to add it already for appium to support bidi well.

### CODE REVIEW

**Comment by christian-bromann** [comment]
I had a conversation recently with @whimboo about `webSocketUrl` being a bit ambiguous: boolean in requested capabilities and string in received capabilities. I couldn't find the resolution to this conversation anymore but this is how it is currently defined in the spec.

**Review by boneskull — CHANGES_REQUESTED** [review]
@jlipps I think `webSocketUrl` needs to be added to `@appium/types/lib/constraints.js`, then LGTM

**Comment by jlipps** [comment]
@christian-bromann agree that it is not as clear a name as something like `bidiEnabled` or whatever

**Comment by jlipps** [comment]
@boneskull updated

**Comment by boneskull** [comment]
...that build failure looks unrelated.  did you pull in the "e2e tests run in parallel" changeset?  if so, we may want to revert it.

**Comment by boneskull** [comment]
(it may also be a network burp)

**Comment by jlipps** [comment]
This is on top of almost latest master, so probably. I'm rerunning the failed jobs.

**Comment by whimboo** [comment]
> I had a conversation recently with @whimboo about `webSocketUrl` being a bit ambiguous: boolean in requested capabilities and string in received capabilities.

Yes, this is right.

**Comment by jlipps** [comment]
@boneskull how come I see extraneous changes in this PR? are these changes not actually in master yet?

**Comment by boneskull** [comment]
@jlipps I clicked the update button, which created a merge commit, unfortunately. Just rebase onto master to get rid of it.

**Comment by boneskull** [comment]
I rebased it.  looks like the "Update & Rebase" is in the dropdown and the default behavior is to merge.

**Comment by jlipps** [comment]
I'm still confused why I see changes that I didn't make. Is it prettier-related? At any rate, I think we can merge this.

**Pull request merged**
