### PR TITLE
feat(appium): add easy management of Flutter driver

### PR DESCRIPTION
**Pull request by eglitise**
## Proposed changes

Now that the Flutter driver is moved under the Appium repo, it only makes sense that the Appium CLI should reflect this. This PR allows the Flutter driver to be managed using just its automation name (e.g. `appium driver install flutter`)

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [X] I have signed the CLA
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
We probably don't want to do that as we are not sure about the future of this driver. Yes, we have picked it up, and moved under the org, although the downstream technology it uses for elements location is not being developed anymore and we don't have anyone who wants to contribute there to ensure further compatibility with WebDriverAgent protocol/Appium.

We have quite a similar situation with the Windows driver.

**Comment by eglitise** [comment]
Fair enough. Perhaps then, to align it with the Windows driver, I could instead move its listing in the documentation to the Other drivers section?

**Comment by mykola-mokhnach** [comment]
> Fair enough. Perhaps then, to align it with the Windows driver, I could instead move its listing in the documentation to the Other drivers section?

Maybe. WDYT @KazuCocoa ?

**Comment by eglitise** [comment]
It was originally already under Other drivers, but I moved it to Official drivers as part of #19528. So I suppose I could just move it back.

**Comment by KazuCocoa** [comment]
I think the flutter driver can be the same as windows driver

**Comment by eglitise** [comment]
Ok - closing this in favor of #19550.

**Pull request closed without merging**
