### PR TITLE
PlistBuddy fails to get Xcode version in some cases 

### PR DESCRIPTION
**Pull request by tarunsujit**
#4809 added a method to handle spaces in path

### CODE REVIEW

**Comment by bootstraponline** [comment]
Please squash to one commit.

**Comment by bootstraponline** [comment]
```
git reset --soft head~5
git commit -am "PlistBuddy fails to get Xcode version when there are spaces in path"
git push -f
```

**Comment by tarunsujit** [comment]
@bootstraponline Thanks but I think I some other issue to do that. Can revert back my pull request and create a new request?

**Comment by tarunsujit** [comment]
Closing this and will create a new request as there are multiple commits in this and i face some problem with squashing the multiple commits.

**Pull request closed without merging**
