### PR TITLE
Improves grammar and formatting in the readme file

### PR DESCRIPTION
**Pull request by brendankirby**
## Proposed changes

I made some grammar and formatting improvements in the readme file. 
## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by imurchie** [comment]
This seems like an improvement. Can you squash into a single commit?

**Comment by jlipps** [comment]
Agreed. However we should probably axe the Firefox OS language since neither Firefox OS nor our support for it is functional anymore.

**Comment by jlipps** [comment]
@brendankirby I'm sorry another doc update made it in before we had the chance to merge yours, which generated some conflicts. Are you able to rebase for us?

**Comment by imurchie** [comment]
Ack! We lost track of this one. @brendankirby can you squash into a single commit? Then we can get it in!

**Comment by brendankirby** [comment]
Sorry, I'm not sure if I'm doing this right. Do I checkout my forked repo, `rebase -i origin/master`, and then squash commits?

**Comment by imurchie** [comment]
You should be able to `rebase -i 52830216f61b23c8b46d4c6a3d446aed9b8d69ef` and then choose one and squash the rest of the commits. The interactive command is unusually well self-documented (for git).

**Comment by jlipps** [comment]
Sorry @brendankirby we made too many other docs updates and this can no longer merge cleanly. If you'd like to rebase your patch we'll still accept it.

**Pull request closed without merging**
