### PR TITLE
Add changelog entry for 1.5.3

### PR DESCRIPTION
**Pull request by imurchie**
Add changelog for 1.5.3. Once merged and released, will cherry pick into master.

### CODE REVIEW

**Comment by jlipps** [comment]
👍

**Comment by SrinivasanTarget** [comment]
@imurchie - Can you please add --session-override fix as well?

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/pull/6445

**Comment by imurchie** [comment]
Certainly! Must have missed it.

**Pull request merged**
