### PR TITLE
Add remoteAdbHost to caps.md

### PR DESCRIPTION
**Pull request by dpgraham**
(related to https://github.com/appium/appium-android-driver/pull/241)

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Review by imurchie — APPROVED** [review]

**Review by jlipps — APPROVED** [review]
looks good, though let's not merge till the other PR is published

**Comment by serggl** [comment]
this is good to merge now I believe

**Comment by dpgraham** [comment]
We'll merge it after we publish a new version of appium.

**Pull request merged**
