### PR TITLE
Add Codecov badge to README

### PR DESCRIPTION
**Pull request by thomasrockhu**
## Proposed changes
Tom from Codecov here. I thought I would go ahead and add the Codecov badge here in case it's useful!

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments
N/A

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Thanks, but this repository does not have it https://github.com/appium/appium/search?q=codecov (and previously a Pr was closed)

**Comment by mykola-mokhnach** [comment]
Unfortunately we have decided to remove codecov integration as its nodejs bindings were unmaintained for more than a year and we did not get any response about the project state after creating an issue there.

**Comment by thomasrockhu** [comment]
@mykola-mokhnach, I'm sorry to hear that. Although you have made that decision, would you be able to link where the issue was created? I would hope that we can make changes for future developers and teams.

**Comment by mykola-mokhnach** [comment]
Sorry, there is some service naming confusion. The original [issue](https://github.com/appium/appium/issues/14648) was about Coveralls, although the decision was to not add any new coverage-related dependencies for now.

**Comment by thomasrockhu** [comment]
@mykola-mokhnach got it! Let me know if that changes, I'd love to be helpful.

**Pull request closed without merging**
