### PR TITLE
WIP: example of retaining history for monorepo

### PR DESCRIPTION
**Pull request by boneskull**
## Proposed changes

I'm opening this PR so I can show an example of what retaining the history of other projects would look like when collapsing into a monorepo.  If we just copy files, of course, we lose all history.  If it is not important to retain the history, then we can skip this step.

This PR pulls `appium-doctor` into `packages/appium-doctor`.  No changes have been made to the code other than moving the files.  The files were moved via a commit in my `appium-doctor` working copy, then this changeset was merged into the `appium` repo.

Note that it's not possible to _rebase_ and retain the history, as this would require each changeset in `appium-doctor` to have _always_ been operating on files in `packages/appium-doctor` to avoid many, many conflicts. 

If doing this "for reals," we'd want the changeset added to `appium-doctor` to actually get pushed to that repo in some branch.

Please let me know what you think of this strategy.

Ref: #14441

cc @christian-bromann 

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by boneskull** [comment]
(do not bother running checks on this code)

**Comment by boneskull** [comment]
the main drawback I'm aware of: it adds a merge commit, so maybe less nice if you're trying to keep the history merge-free.

it's possible that some dumb git tools will fail to understand "file history" and conflate `package.json` with `packages/appium-doctor/package.json`, due to the unrelated histories.  I'll try to confirm if it's a problem.

w/r/t rebasing: when you rebase _n_ commits from one branch to another, rebasing starts with the oldest "new" changeset, and moves forward up to the latest changeset.  so the first thing it'd do is try to merge the initial commit of `appium-doctor` onto the current state of the `2.0` branch.  the initial commit of `appium-doctor` has its own `package.json` in the root (and probably many other conflicting filenames).  _every changeset_ in `appium-doctor` builds on this, so _every changeset_ will have conflicts which will need to be manually resolved when rebasing.  there _might_ be a git resolution strategy that avoids this, but I have no idea if such a thing exists or how to use it.

merging _would_ have this same problem if I didn't add a changeset in `appium-doctor` which _moved_ the entire project into a `packages/appium-doctor` subdirectory.  when merging, git doesn't care about the old changesets, e.g., when `appium-doctor`'s `package.json` was in its root--it only cares about the state of the repo in the merge's two parent changesets.  because there is no `packages/appium-doctor` in `2.0`, there are no conflicts.

**Comment by jlipps** [comment]
ah, i get it now. yeah in general we prefer rebasing but for something like this a merge might be OK. i'm also honestly not too opposed to just bringing it in one commit and saying go look at this old repo for history... what do you think @mykola-mokhnach ?

**Comment by mykola-mokhnach** [comment]
> ah, i get it now. yeah in general we prefer rebasing but for something like this a merge might be OK. i'm also honestly not too opposed to just bringing it in one commit and saying go look at this old repo for history... what do you think @mykola-mokhnach ?

I am fine with either approach

**Comment by boneskull** [comment]
it's easier to just copy the files, of course.

of the repos that we intend to live in the monorepo, are there any that you'd specifically like to retain history for?

it's certainly possible to say "go look over there" if you want to see the history, but such a direction is not well-supported by IDEs 😄

**Pull request closed without merging**
