### PR TITLE
chromedriver kill fix

### PR DESCRIPTION
**Pull request by sebv**
Fixes https://github.com/appium/appium/issues/3484 (also requires https://github.com/appium/appium/commit/921077a39d16b83a72dc12f6493a2cc155f98b6e)

@jlipps can you check looks like the both ChromeDriver kill methods were broken, and didLaunch wasn't set for Chrome case triggering errors down the line.

### CODE REVIEW

**Comment by ukostas** [comment]
Hi, looks like killing old chromedriver cmd on windows doesn't work and hence new driver cannot start on same port, here is log on this:
```log
2015-02-15 21:54:25:046 - info: [debug] Ensuring Chromedriver exists
2015-02-15 21:54:25:047 - info: [debug] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "P
ID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %b))
2015-02-15 21:54:25:055 - info: [debug] No old chromedrivers seemed to exist
2015-02-15 21:54:25:055 - info: [debug] Spawning chromedriver with: C:\Users\Kostas\AppData\Roaming\npm\node_modules\appium\build\chromedriver\windows\chromedriver.exe
2015-02-15 21:54:25:067 - info: [debug] [CHROMEDRIVER] Starting ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf) on port 9515
Only local connections are allowed.
2015-02-15 21:54:25:068 - info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"a
ndroidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"emulator-5554"}}}}
2015-02-15 21:54:25:070 - info: [debug] [CHROMEDRIVER STDERR] [0.003][SEVERE]: bind() returned an error: Only one usage of each socket address (protocol/network address/port) is normally permitted. (0
x2740)
[0.003][WARNING]: Unknown error 10038 mapped to net::ERR_FAILED
2015-02-15 21:54:25:071 - info: [debug] [CHROMEDRIVER] Port not available. Exiting...
```
I did some changes locally (from [line 73](https://github.com/appium/appium/pull/3909#discussion-diff-19480433R73)) and it works for me:
* [**%**a instead of %%a] (https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/for.mspx?mfr=true)
* I think last part should contain PID variable %a instead of %b
```javascript
 if (isWindows) {
   cmd = "FOR /F \"usebackq tokens=5\" %a in (`netstat -nao ^| findstr /R /C:\"" + this.proxyPort + " \"`) do (" +
            "FOR /F \"usebackq\" %b in (`TASKLIST /FI \"PID eq %a\" ^| findstr /I chromedriver.exe`) do (" +
              "IF NOT %b==\"\" TASKKILL /F /PID %a" +
            ")" +
          ")";
```
Could you please take a look and apply change if it makes sense?
Thanks!

**Comment by jlipps** [comment]
@0x1mason ^^

**Comment by 0x1mason** [comment]
Yeah, this looks good.

**Comment by jlipps** [comment]
ok, i'll leave it up to @sebv to apply the change described before we merge this

**Comment by ukostas** [comment]
Thanks for checking this!

**Pull request merged**
