### PR TITLE
chore(): set engines to minimum Node.js v14.17.0

### PR DESCRIPTION
**Pull request by boneskull**
Given that the latest version of `npm` does not support v14.0.0--and I'm seeing lots of support for Node.js < v14.17.0 getting dropped--we should do the same. We already have multiple PRs held up due to this.

Strictly speaking, this is a breaking change. If we agree, then I will rewrite the commit message to reflect this, and all packages (except `appium`) will have their major version bumped on next publish post-merge.

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* master
  * **PR #17811** <a href="https://app.graphite.dev/github/pr/appium/appium/17811" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium/17811?utm_source=stack-comment).

**Review by jlipps — APPROVED** [review]
yep should appropriately mark as a breaking change. we should probably also have a policies page in our docs that articulates our policy about node version support.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium#requirements
https://github.com/appium/appium/blob/master/packages/appium/docs/en/intro/requirements.md ? (for documentation)

**Comment by boneskull** [comment]
FWIW, this is what Lerna will do when publishing:

 - appium: 2.0.0-beta.46 => 2.0.0-beta.47
 - @appium/base-driver: 8.7.3 => 9.0.0
 - @appium/base-plugin: 1.10.5 => 2.0.0
 - @appium/doctor: 1.16.28 => 2.0.0
 - @appium/docutils: 0.0.13 => 0.1.0
 - @appium/driver-test-support: 0.2.1 => 0.3.0
 - @appium/eslint-config-appium: 7.0.0 => 8.0.0
 - @appium/execute-driver-plugin: 2.0.6 => 3.0.0
 - @appium/fake-driver: 4.2.2 => 5.0.0
 - @appium/fake-plugin: 2.1.3 => 3.0.0
 - @appium/gulp-plugins: 7.0.8 => 8.0.0
 - @appium/images-plugin: 1.3.7 => 2.0.0
 - @appium/opencv: 1.0.13 => 2.0.0
 - @appium/plugin-test-support: 0.2.1 => 0.3.0
 - @appium/relaxed-caps-plugin: 1.0.0-beta.13 => 1.0.0-beta.14
 - @appium/schema: 0.0.9 => 0.1.0
 - @appium/support: 2.61.1 => 3.0.0
 - @appium/test-support: 2.0.2 => 3.0.0
 - @appium/types: 0.5.0 => 0.6.0
 - @appium/universal-xml-plugin: 1.0.0-beta.15 => 1.0.0-beta.16

**Comment by boneskull** [comment]
GTG? @jlipps ?

**Comment by jlipps** [comment]
wow look at all those major bumps. i like the feeling of major bumps not really meaning much other than a breaking change. seems reasonable to me!

**Review by jlipps — APPROVED** [review]

**Pull request merged**
