### PR TITLE
Update js example in touch-actions.md

### PR DESCRIPTION
**Pull request by isnifer**
## Proposed changes

Fix js example of scroll

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

Current example for js throws an error like:
```bash
{ [Error: undefined is not an object (evaluating 'direction[0].toUpperCase')] message: 'undefined is not an object (evaluating \'direction[0].toUpperCase\')', type: 'RuntimeError', seleniumStack: { message: 'An error occurred while executing user supplied JavaScript.', orgStatusMessage: 'undefined is not an object (evaluating \'direction[0].toUpperCase\')', status: 17, type: 'JavaScriptError' } }
```

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by isnifer** [comment]
Hey @imurchie, @jlipps! Please, update wrong documentation

**Comment by isnifer** [comment]
Okay, in that case problem on the code

**Comment by imurchie** [comment]
What system are you using? Something may have been messed up.

**Comment by isnifer** [comment]
macOS Sierra

**Comment by imurchie** [comment]
Can you post the logs? So we can see the configuration, etc.?

**Comment by isnifer** [comment]
No problem, I will do it in an hour. Currently I'm drinking beer with my
friends)

**Comment by imurchie** [comment]
:) If it weren't noon here I would be doing the same!

**Comment by isnifer** [comment]
@imurchie I've added log here - https://gist.github.com/isnifer/4ac83a2e0206fe56be9c3fc266a559b9

**Comment by imurchie** [comment]
What client are you using? This request looks wrong:

```
[HTTP] --> POST /wd/hub/session/77e3bbe5-ffe1-41e6-9c45-494e3ae96135/execute {"script":"mobile: scroll","args":[[{"direction":"down","element":"14"}]]}
```

I would expect to not have the args inside nested arrays. It should just be a bare object, like:

```
[HTTP] --> POST /wd/hub/session/7c6da5db-5e8e-4973-94be-cefed2faa06e/execute {"script":"mobile: scroll","args":{"direction":"down"}}
```

**Comment by isnifer** [comment]
I sent request like in docs. I think client is not important, the code matters. But I'm using appium from npm, 1.6.0.

**Comment by imurchie** [comment]
The client matters because it is constructing the payload sent to the server. What language are you using? And client library for sending commands?

**Comment by isnifer** [comment]
@imurchie I'm using javascript and [appium@1.6.0](https://www.npmjs.com/package/appium) from npm. But! It really doesn't matter.
Look, I sent bad request because docs say: "Hey, man, you wanna swipe in js, just send `driver.execute("mobile: scroll", [{direction: 'down'}])`". It's not a problem with a client, it's not a problem with constructing a request. It's a bad request provided by docs.
So, I think we need to improve code of appium or docs.

**Comment by imurchie** [comment]
But it _is_ a problem with the client. If a client is taking 

```js
driver.execute("mobile: scroll", [{direction: 'down'}])
```

And creating the failing request

```
[HTTP] --> POST /wd/hub/session/77e3bbe5-ffe1-41e6-9c45-494e3ae96135/execute {"script":"mobile: scroll","args":[[{"direction":"down","element":"14"}]]}
```

That is **wrong**. The documentation may need to be changed (and I'm fine with changing it, other than the direction being in an array), but that doesn't change the fact that the client is doing the wrong thing. So I'm asking what language binding you are using so that too can be changed.

**Comment by isnifer** [comment]
If I suggest changing js example, of course, I'm using js.

**Comment by imurchie** [comment]
Yes, but there are many ways to connect to the server through JavaScript. `wd`, `webdriver.io`, bare http calls, whatever.

**Comment by isnifer** [comment]
Oh, understood. I'm using webdriver.io

**Comment by imurchie** [comment]
Ah. Ok. The documentation was written before that library was around. Does it work to use

```js
driver.execute('mobile: scroll', {direction: 'down'})
```

**Comment by isnifer** [comment]
Okay, I tried next code:
```js
const { value: { ELEMENT: homeLoginButtonElement } } = await driver.element(homeLoginButtonId)
await driver.execute('mobile: scroll', {direction: 'down', element: homeLoginButtonElement})
```

And everything works fine:
```
[HTTP] --> POST /wd/hub/session/34789184-24b9-4d9d-8625-f43cb6eaef26/execute {"script":"mobile: scroll","args":[{"direction":"down","element":"13"}]}
```

**Comment by imurchie** [comment]
Cool. Can you take the array out of your update, and then we'll get this in! Thanks, and sorry for the long-winded confusion.

**Comment by isnifer** [comment]
No problem, the main thing that we found correct solution

**Comment by imurchie** [comment]
Awesome!

**Pull request merged**
