### PR TITLE
chore(ci): add job to disallow merges of PRs

### PR DESCRIPTION
**Pull request by boneskull**
...if it has the "On Hold" label

### CODE REVIEW

**Comment by boneskull** [comment]
This works

**Comment by boneskull** [comment]
FWIW, the action needs "write" perms because it rewrites the status of its own previous checks. I think this may cause any other jobs that depend on it to re-run?  I'm not entirely sure.  Anyway, this seems safe enough.

**Review by jlipps — APPROVED** [review]
something tells me you may be the only one to use this ^ _ ^ but looks good!

**Comment by boneskull** [comment]
@jlipps yeah, I haven't seen anyone else use `On Hold`, but I felt nervous about it.

**Pull request merged**
