### PR TITLE
#4835 -- add logType server and retrive server log

### PR DESCRIPTION
**Pull request by hyeung-trulia**
add logType server and retrive server log

### CODE REVIEW

**Comment by jlipps** [comment]
:+1: for the change. @sebv didn't we have a different tmp file thing we made?

**Comment by sebv** [comment]
Here https://github.com/appium/appium-support/blob/master/lib/tempdir.js, instead of `tmp`.

**Comment by sebv** [comment]
test this please

**Comment by jlipps** [comment]
@hyeung-trulia yes please use the tempdir methods from our 'appium-support' package to keep things consistent.

**Comment by hyeung-trulia** [comment]
@sebv and @jlipps where to put a unit test in? do you have a sample unit test on how test logging? We tested with our local grid and it's working fine.

**Comment by jlipps** [comment]
@hyeung-trulia I would add a new -spec as a functional test for ios and android. we already have tests for different log types. see:

* test/functional/ios/testapp/basics/calc-app-2-specs.js
* test/functional/android/apidemos/basic-specs.js

(notice that for each we have a test that the log type is returned, and that we can get the log)

**Comment by jlipps** [comment]
closing for now, @hyeung-trulia please resubmit with some tests. thanks!

**Pull request closed without merging**
