### PR TITLE
bring in new appium-chromedriver with chromedriver 2.16

### PR DESCRIPTION
**Pull request by jlipps**
cc @bayandin. I tried to run chrome specs with this, but got some failures. I'm not sure if this chromedriver actually works very well. Have you used it much @bayandin?

I was testing against the Browser app in api 21

### CODE REVIEW

**Comment by jlipps** [comment]
downloading chrome now to try chrome itself

**Comment by jlipps** [comment]
yeah it doesn't seem like click is working. pretty basic stuff.

**Comment by bayandin** [comment]
Hey @jlipps,

I checked appium 1.4.0 with chromedriver 2.16 and real nexus 5 with chrome 43 on a couple tests from our project and it works.
Could you please provide a failed test case for investigating.

Thanks!

**Comment by jlipps** [comment]
@bayandin working for me too on a real device. It's not working with the Browser app on API level 21 emulators, or Chrome beta on API level 21 emulators. Downloading Android SDK updates now to see if that helps.

**Comment by jlipps** [comment]
also doesn't work on API level 22 with latest emu, so... seems like chromedriver 2.16 breaks Android browser support, or emulator support, for click

**Comment by jlipps** [comment]
@bayandin here's what I ran (with an emulator loaded):

```
DEVICE=android BROWSER_NAME=browser mocha -t 60000 -R spec test/functional/android/chrome/chrome-specs.js -g "@skip-chrome|alert" -i
```

**Pull request closed without merging**
