### PR TITLE
sudo necessary? / clearer example path

### PR DESCRIPTION
**Pull request by rompic**
- i had to run it with sudo in order to have the file changed.
- changed the example path to make it clearer

### CODE REVIEW

**Comment by moizjv** [comment]
Can one of the admins verify this patch?

**Comment by imurchie** [comment]
I would rather this remain as it was, and add a note that, depending on where your Appium server is installed, you may need to run the command as superuser. Using `sudo`, though, should _not_ be the default.

**Comment by rompic** [comment]
Fine with me. Maybe the script could also check whether it ran successfully, as there is currently no error if it fails.

**Comment by imurchie** [comment]
Unfortunately, in the shuffle of Appium 1.5, this PR got very messed up. If the problem that it was meant to solve persists in 1.5, can you either (a) open an issue explaining the problem and the solution, or (b) open a new PR?

We apologize for the mess up. :(

**Comment by ntulele** [comment]
Issue still exists:  The plist file is not changed until the script is executed using sudo
Evidence: Executing twice without sudo didn't change plist file's timestamp; and output of the script indicated the EnvVars entry still did not exist.
After execution using sudo, timestamp was updated; and entry reported as existing upon 2nd execution.

**Pull request closed without merging**
