### PR TITLE
Fixed fail to find xcode -- fixes #2884

### PR DESCRIPTION
**Pull request by 0x1mason**
This change should provide a more robust way to find xcode. I'm not sure if the problem is xcode-select or Node's stdout buffering, but this code side steps that altogether.

### CODE REVIEW

**Comment by 0x1mason** [comment]
retest please

**Comment by jimberley** [comment]
When will this be pushed out to the world?

**Comment by 0x1mason** [comment]
Should be available now.

**Comment by 0x1mason** [comment]
You mean as part of a release?

**Comment by jimberley** [comment]
Yessir. As a release and/or available on SAUCELabs.

**Comment by 0x1mason** [comment]
I'm not sure right now, but 4 weeks at the longest.  We're meeting tomorrow
to discuss a new approach so we can get small fixes out faster, so I might
have better news soon. Feel free to ping me here on Wed.  You can also
email me at eric@saucelabs.com.

**Comment by jimberley** [comment]
It's not a big deal since I've just rolled our Appium version back to 1.3.4 for our test runs.

I would be a BIG fan of more frequent releases of Appium since we are super dependent on it for our testing here at Yammer. We _love_ Appium, and when it breaks, it breaks our little hearts. Thank you.

**Comment by 0x1mason** [comment]
@jimberley Glad to hear you like Appium. Do you mind if I asked why you rolled it back? Did you experience this particular issue because of an upgrade?

**Comment by jimberley** [comment]
I rolled back because I know that 1.3.4 didn't have this issue and we're not seeing any issues with SAUCELabs after doing so. The issue happened some time over the weekend, I'm not sure why. Maybe SAUCE just got the latest release from 9 days ago?

**Comment by 0x1mason** [comment]
Gotcha.  1.3.6 went out late last week both for general release and on
Sauce. Thursday, I think, for Sauce.

Glad you've got something working for you and I hope we'll have more good
news for you soon.

**Comment by kani19** [comment]
I still see this issue on 1.3.7

**Comment by jlipps** [comment]
@kani19 please try 1.4 beta

**Pull request merged**
