### PR TITLE
Update parallel-test.md in case using ChromeDriver

### PR DESCRIPTION
**Pull request by zcmgyu**
## Proposed changes

Set a unique ChromeDriver port for each parallel session is required for parallel execution.
ChromeDriver port conflict causes ChromeDriver to crash during startup in parallel execution.
So, I updated the document for this part.

```
[Chromedriver] Spawning chromedriver with: /Users/hc499/.nvm/versions/node/v15.8.0/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v93.0.4577.63 --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[debug] [Chromedriver] Chromedriver version: '93.0.4577.63'
[Chromedriver] Chromedriver v. 93.0.4577.63 supports W3C protocol, but MJSONWP one has been explicitly requested
[debug] [Chromedriver] [STDOUT] Starting ChromeDriver 93.0.4577.63 (ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}) on port 8000
[debug] [Chromedriver] [STDOUT] Only local connections are allowed.
[debug] [Chromedriver] [STDOUT] Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8000
[Chromedriver] [STDERR] [1632815093.651][SEVERE]: bind() failed: Address already in use (48)
[Chromedriver] [STDERR] [1632815093.651][INFO]: listen on IPv4 failed with error ERR_ADDRESS_IN_USE
[debug] [Chromedriver] [STDOUT] IPv4 port not available. Exiting...
[Chromedriver] Chromedriver exited unexpectedly with code 1, signal null
[debug] [Chromedriver] Changed state to 'stopped'
[debug] [Chromedriver] Error: ChromeDriver crashed during startup.
```

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Could you please sign the CLA?

**Comment by zcmgyu** [comment]
@mykola-mokhnach I tried but still not passed this CLA sign. Let me finish it.

**Comment by zcmgyu** [comment]
@mykola-mokhnach Covered. I must add my Github account to our company list.
Please check this PR. Thanks.

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
Thanks, merged

**Comment by zcmgyu** [comment]
@mykola-mokhnach Thanks :D

**Pull request merged**
