### PR TITLE
use appium-support package for system detection

### PR DESCRIPTION
**Pull request by jlipps**
Starting to move some code over. I can't publish the appium-support package to NPM yet, though, so this can't be merged till that's done and the package.json ref updated

### CODE REVIEW

**Comment by jlipps** [comment]
cc @sebv can you give me push rights to npm for this repo

**Comment by jlipps** [comment]
ok, this is ready for review and merge @sebv

**Comment by sebv** [comment]
lgtm.

**Comment by jlipps** [comment]
k, will merge once we've got 1.3.5 out

**Pull request merged**
