### PR TITLE
Update start-recording-screen.yml

### PR DESCRIPTION
**Pull request by edizzyy**
It can be confusing to pass the parameters without adding the given parameters under "options" - this is not stated anywhere in the documentation.

## Proposed changes

Add an explanation to use "options" parameter before using the json parameters on the documentation

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ediz12** [comment]
I am unsure how you would fix the documentation here - is there a specific documentation I have to follow based on appium's documentation style according to the build error logs?

**Comment by imurchie** [comment]
There's no documentation on it, at the moment.

The problem you're having, though, is that there is no `short_description` attribute for that field, so the parser doesn't know what to do.

The way that this has been solved in the past can be seen in the JSON parameters for `touch-perform`: https://github.com/appium/appium/blob/master/commands-yml/commands/interactions/touch/touch-perform.yml#L102-L116

**Comment by ediz12** [comment]
> There's no documentation on it, at the moment.
> 
> The problem you're having, though, is that there is no `short_description` attribute for that field, so the parser doesn't know what to do.
> 
> The way that this has been solved in the past can be seen in the JSON parameters for `touch-perform`: https://github.com/appium/appium/blob/master/commands-yml/commands/interactions/touch/touch-perform.yml#L102-L116

Fixed it accordingly - I believe it makes more sense now.

**Review by imurchie — APPROVED** [review]
Thanks for this! Definitely an improvement.

**Pull request merged**
