### PR TITLE
docs(appium): add strategic partner browserstack

### PR DESCRIPTION
**Pull request by jlipps**

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]
Would the building docs for non en fail?

**Review by mykola-mokhnach — APPROVED** [review]
LGTM after docs building is fixed

**Comment by eglitise** [comment]
I think I managed to fix the problem with docs building and asset paths [in my branch](https://github.com/appium/appium/compare/jlipps/strat-partner-announce...eglitise:appium:partner-announce). Basically, instead of using the custom `copy-assets.js` script, it's easier to rely on Material for MkDocs's own way of copying assets, by just placing them in the `overrides` directory, [as described here](https://squidfunk.github.io/mkdocs-material/customization/?h=override#setup-and-theme-structure). It worked fine, so I figured I would delete the custom script as well.

Other notes:
* The current implementation of color-specific images did not work for me. I changed to the [Material for MkDocs's documented approach](https://squidfunk.github.io/mkdocs-material/reference/images/?h=dark+mo#light-and-dark-mode) and it is now working.
* Color-specific images were removed from the footer, since the footer color stays the same regardless of the theme.

**Comment by jlipps** [comment]
awesome, good finds and thanks @eglitise !

**Pull request merged**
