### PR TITLE
Update examples for WebdriverIO

### PR DESCRIPTION
**Pull request by WillBrock**
## Proposed changes

With the release of WebdriverIO version 5 back in December there were a lot of command updates/changes.

This updates the examples with the new or updated commands.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dpgraham** [comment]
Awesome! Thank you for this @WillBrock

**Comment by dpgraham** [comment]
@WillBrock looks like there's some invalid YAML:

```
17:51:59] Invalid YAML file: '/home/travis/build/appium/appium/commands-yml/commands/device/network/gsm-call.yml'
[17:51:59] bad indentation of a mapping entry at line 12, column 5:
[17:51:59]         javascript_wdio:
[17:51:59]         ^
[17:51:59] YAML errors found. Due to the limitations of YAML linting, the error 
[17:51:59] is most likely in the line immediately before the line reported.
```

**Comment by WillBrock** [comment]
Updated.

**Review by dpgraham — APPROVED** [review]
Will merge once checks passed.

**Pull request merged**
