### PR TITLE
Lazy load drivers upon request

### PR DESCRIPTION
**Pull request by imurchie**
## Proposed changes

I do not have time to go in depth into #11067, and I especially think the structure of the driver definitions needs to be discussed a lot more. This is work that should be included in the [Appium 2.0](https://github.com/appium/appium/issues/7175) efforts.

However, there is a lot of value in _not_ having all the drivers imported at load time. This decreases the memory footprint, for one thing, as well as load time. It also means that we aren't loading drivers we do not control, by default.

For instance, using Node 11 (so `Buffer()` is deprecated) Appium will print a deprecation warning, because the published version of [appium-sbd](https://github.com/Samsung/appium-sdb), a dependency of [appium-tizen-driver](https://github.com/Samsung/appium-tizen-driver), which is out of our control, uses an older version of [source-map-support](https://www.npmjs.com/package/source-map-support), and Node loads it instead of the version the `AppiumDriver` includes.

Who knows where else this is happening.

**This PR**
1. Removes the static imports and moves to `require`-ing the drivers as they are requested.
1. Changes the `DRIVER_MAP` to use `automationName` as the keys, so we can just get the driver rather than cycling through to find the correct one.
1. Only gets the version of the driver when necessary.
1. Puts the Appium version into the driver version log line.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Brilliant, launching time became faster on my local machine 👍 

But I faced below error. (I haven't diged it yet). The capability worked on current master.
Is something missing in detection process?

```
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1549416564893 (10:29:24 GMT+0900 (Japan Standard Time))
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1549416564895 (10:29:24 GMT+0900 (Japan Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Could not find a driver for automationName 'uiautomator2' and platformName 'android'. Please check your desired capabilities.
[debug] [W3C]     at AppiumDriver.getDriverAndVersionForCaps (/Users/kazu/GitHub/appium/lib/appium.js:204:11)
[debug] [W3C]     at AppiumDriver.getDriverAndVersionForCaps [as createSession] (/Users/kazu/GitHub/appium/lib/appium.js:267:66)
[debug] [W3C]     at AppiumDriver.executeCommand (/Users/kazu/GitHub/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:301:19)
[debug] [W3C]     at AppiumDriver.executeCommand (/Users/kazu/GitHub/appium/lib/appium.js:419:26)
[debug] [W3C]     at executeCommand (/Users/kazu/GitHub/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:352:34)
[debug] [W3C]     at asyncHandler (/Users/kazu/GitHub/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:489:15)
[debug] [W3C]     at Layer.handle [as handle_request] (/Users/kazu/GitHub/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C]     at next (/Users/kazu/GitHub/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [W3C]     at Route.dispatch (/Users/kazu/GitHub/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [W3C]     at Layer.handle [as handle_request] (/Users/kazu/GitHub/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C]     at /Users/kazu/GitHub/appium/node_modules/express/lib/router/index.js:281:22
[debug] [W3C]     at Function.process_params (/Users/kazu/GitHub/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [W3C]     at next (/Users/kazu/GitHub/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C]     at logger (/Users/kazu/GitHub/appium/node_modules/morgan/index.js:144:5)
[debug] [W3C]     at Layer.handle [as handle_request] (/Users/kazu/GitHub/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C]     at trim_prefix (/Users/kazu/GitHub/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [W3C]     at /Users/kazu/GitHub/appium/node_modules/express/lib/router/index.js:284:7
[debug] [W3C]     at Function.process_params (/Users/kazu/GitHub/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [W3C]     at next (/Users/kazu/GitHub/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C]     at /Users/kazu/GitHub/appium/node_modules/body-parser/lib/read.js:130:5
[debug] [W3C]     at invokeCallback (/Users/kazu/GitHub/appium/node_modules/raw-body/index.js:224:16)
[debug] [W3C]     at done (/Users/kazu/GitHub/appium/node_modules/raw-body/index.js:213:7)
[debug] [W3C]     at IncomingMessage.onEnd (/Users/kazu/GitHub/appium/node_modules/raw-body/index.js:273:7)
[debug] [W3C]     at IncomingMessage.emit (events.js:197:13)
[debug] [W3C]     at endReadableNT (_stream_readable.js:1129:12)
[debug] [W3C]     at processTicksAndRejections (internal/process/next_tick.js:76:17)
[HTTP] <-- POST /wd/hub/session 500 10 ms - 800
```

**Comment by imurchie** [comment]
Ok. That'll be a case issue. Investigating.

**Comment by imurchie** [comment]
Updated for the case of the `automationName` capability (`platformName` was already properly handled) and add unit tests for both of those cases.

**Review by KazuCocoa — APPROVED** [review]
Looked and worked to me

**Comment by KazuCocoa** [comment]
Just my curiosity.
Is there another way to make the initial time faster?
(I haven't traced which processes take much time in our initialisation phase.)

**Review by jlipps — APPROVED** [review]
this is a brilliant idea.

**Comment by KazuCocoa** [comment]
I see. thanks! > https://github.com/appium/appium/pull/12127#issuecomment-460897015

**Pull request merged**
