### PR TITLE
ignore lib

### PR DESCRIPTION
**Pull request by Bamieh**
no need to send the unbuilt files to npm

## Proposed changes

Ignore `lib` folder for npm releases since the `build` folder is the entry file of the project.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jlipps** [comment]
I think we should still send the source files to NPM, that way it's easier to debug from within an install. exceptions show line numbers in the lib files, so if we don't include those in the module, I think it might be confusing for people who are looking at an npm install rather than a git clone.

**Comment by Bamieh** [comment]
@jlipps sadly my errors throw at babel level, `_generatorAsync` or such.  Sourcemaps are used solve this issue. Digging through source code is a very niche use case IMHO, people who dig through the sourcecode will also dig it through github. Its a good practice to keep the npm package size at a minimum.

**Comment by imurchie** [comment]
I'm good with this. I thought we had done it a long time ago, actually.

_However_, this will have to be done in all the packages to have any particular affect on package size. The size of the `lib` directory in this repo is negligible in comparison to other factors. Right now it's about 84k while the `release.pdf` file is 80k (and node_modules is 850M).

**Comment by mykola-mokhnach** [comment]
I'd rather keep the `lib` folder, at least for beta releases. It is sometimes quite handy if it is needed to check a quick fix there.

**Comment by jlipps** [comment]
Given the difficulty in making this change project-wide, and the relatively small gain in ignoring lib in npm releases, my feeling is that it's not worth it. If you feel like this should be done though @imurchie I'm OK with it.

**Comment by imurchie** [comment]
I'm ok with not doing it. There are bigger fish to fry in terms of stuff to include/not include. 

Once Babel 7 comes out I have to go through every package to update, so I can adjust things then.

**Comment by imurchie** [comment]
Thanks for the work, though, @Bamieh , and the impulse to get it smaller. Hopefully the next release will be much smaller.

**Pull request closed without merging**
