### PR TITLE
chore(ci): only build on PRs and pushes to 2.0

### PR DESCRIPTION
**Pull request by boneskull**
For every push to a PR, when the PR branch exists on `appium/appium`, a "push" build happens and a "pr" build happens.  The "push" build tests the code in isolation, and the "pr" build tests it as it would be merged into the base branch.  mostly this is just extra work, as the latter type is much more important.  however, the `2.0` branch should be tested every time code is merged into it.

What do we think of this (assuming it works)?

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I'd rather keep it as is for now until we move `2.0` to master

**Comment by boneskull** [comment]
as you can see from the checks, no "push" events there. so this seems to do what it's supposed to, but just want to know if someone can think of a reason why we shouldn't.

**Review by jlipps — APPROVED** [review]

**Review by KazuCocoa — APPROVED** [review]
as my understanding, master branch's actions will keep in https://github.com/appium/appium/tree/master/.github/workflows . This is only for 2.0 branch's actions.
lg

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach what's the reasoning?

To avoid doing extra work after the branch switch. Priorities...

**Comment by boneskull** [comment]
@mykola-mokhnach ah.  well, maybe we should just sit on this until we move `2.0` to `main`.

**Comment by boneskull** [comment]
I'm going to close this, as I am doubting this does what I think it does.  I did something similar in another repo, and checks were not getting triggered on pushes to PR branches.

**Pull request closed without merging**
