### PR TITLE
Add license status and report

### PR DESCRIPTION
**Pull request by xizhao**
In response to JSF adoption of FOSSA for license scanning. @kborchers

### CODE REVIEW

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by triager** [comment]
Can one of the admins verify this patch?

**Comment by xizhao** [comment]
@imurchie FOSSA does automatic Open Source license scanning and compliance automation for your code/dependencies. 

You should have gotten an email about this from Kris last week, but FOSSA is onboarding the JSF right now. A bunch of other JSF projects like Mocha, Grunt, Webpack, etc... have already adopted.

If you want to avoid GH login, feel free to make an account with your email and send Kris a note, and he can invite you to the org.  Unfortunately, those perms are the most conservative we can ask for, as you can't ask for "read-only" code access on the current Github API.

**Comment by kborchers** [comment]
Hi @imurchie, if you ping @jlipps he can give you the rundown on this integration. Thanks!

**Comment by jlipps** [comment]
@imurchie sorry forgot to mention this while I was out of town last week. FOSSA is rad and is what helped us find the GPLed code issue we've been working on.

**Pull request merged**
