### PR TITLE
Added new doc on versioning, branching, and releasing

### PR DESCRIPTION
**Pull request by 0x1mason**
@paymand @bootstraponline @imurchie @jlipps @Jonahss @sebv @tarunsujit 

There isn't much new here, more a formalization of our previous discussions on semantic versioning and trunk-based development.

### CODE REVIEW

**Comment by jlipps** [comment]
:+1:

**Comment by bootstraponline** [comment]
:+1:

**Comment by imurchie** [comment]
:+1:

**Comment by sebv** [comment]
:+1:,  should also expand this to sub-packages.

**Comment by paymand** [comment]
:+1:

**Pull request merged**
