### PR TITLE
basic refresh of docs, just small edits for accuracy and completeness

### PR DESCRIPTION
**Pull request by jlipps**
cc @imurchie @dpgraham

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/pull/7104/files#diff-62f9627bc24ebbde9a78c3aaf4769229R16
@jlipps Can you please update to ```XCUITest```

**Comment by jlipps** [comment]
@SrinivasanTarget i don't understand what you're saying...?

**Comment by SrinivasanTarget** [comment]
@jlipps There is a typo ```XCIUTest``` should be updated as ```XCUITest```.
Here:https://github.com/appium/appium/pull/7104/files#diff-62f9627bc24ebbde9a78c3aaf4769229L16

**Comment by jlipps** [comment]
thanks @SrinivasanTarget, fixed.

**Review by imurchie — APPROVED** [review]
Awesome!

**Comment by SrinivasanTarget** [comment]
LGTM 👍

**Pull request merged**
