### PR TITLE
fix(logger): fix license ref

### PR DESCRIPTION
**Pull request by chenrui333**
relates to https://github.com/appium/appium/pull/20161

https://github.com/appium/appium/blob/3fbc4f1fe07eadf9c7a2ef8fc9f4ba78dc3486a3/README.md?plain=1#L208

### CODE REVIEW

**Comment by KazuCocoa** [comment]
hm, our release script changed to Apache-2.0
https://github.com/appium/appium/commit/339acd345fafa1292c8d286261553fcc6b440e46#diff-6b07e442fc527c911a7841554308068a91cd3aaaf6dc9b34d3a19741d8d393fc

**Comment by KazuCocoa** [comment]
This will bring back to ISC in package.json but next release will set as `Apache-2.0` again. We should fix script side

**Comment by eglitise** [comment]
I'm not sure if configuring lerna to ignore license files will prevent it from changing the actual license line in package.json 🤔 would be great if it did, though

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/pull/20217 will fix this root cause

**Pull request closed without merging**
