### PR TITLE
Sample code

### PR DESCRIPTION
**Pull request by saikrishna321**
## Proposed changes

1. Fixed WDIO sample tests
2. Updated sample-code branch with master

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jlipps** [comment]
This has unrelated commits in it. If we want to merge master to sample-code, that should be done separately so that we can see your changes.

**Comment by saikrishna321** [comment]
@jlipps will close this one PR. will do as you said. 

@dpgraham is there any reason why we have sample-code branch not merged to master for so long?

**Comment by dpgraham** [comment]
@saikrishna321 Yeah we're waiting until the Python and C# samples are finished. I'll revisit this with @imurchie tomorrow though and get this done with.

**Comment by dpgraham** [comment]
@saikrishna321 I just rebased sample-code so now it's just 10 commits.

**Comment by saikrishna321** [comment]
@dpgraham Thanks 👍 i shall resolve the conflicts

**Comment by dpgraham** [comment]
@saikrishna321 I'd recommend rebasing again.

**Comment by dpgraham** [comment]
You'll just need to do a rebase that knocks out my commits (cc90 -> 4687)

**Review by dpgraham — APPROVED** [review]
Looks good. Thanks for this @saikrishna321

**Pull request merged**
