### PR TITLE
fix(docutils): fixes some weirdness with default behavior and the "implies" keyword

### PR DESCRIPTION
**Pull request by boneskull**
- fixes some weird broken CLI arg stuff, I think; see https://github.com/appium/appium-xcuitest-driver/issues/1741
- also squashes an errant warning
- fix some diff logic when writing to `mkdocs.yml`
- add missing `@types/source-map-support` dev dep

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* master
  * **PR #18751** <a href="https://app.graphite.dev/github/pr/appium/appium/18751" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium/18751?utm_source=stack-comment).

**Comment by boneskull** [comment]
@jlipps do you think you can try this against `appium-xcuitest-driver`?  pulling the branch and then using `npm link` should work. e.g.

```bash
appium$ npm link --workspaces
appium$ cd /appium-xcuitest-driver
appium-xcuitest-driver$ npm link @appium/docutils
```

**Comment by jlipps** [comment]
@boneskull doesn't seem to work yet

```
> appium-xcuitest-driver@4.31.0 publish:docs
> appium-docs build --deploy -b docs-site -m 'docs: auto-build docs for appium-xcuitest-driver@%s' --rebase

appium-docs build

Build Appium extension documentation using TypeDoc & MkDocs

Build Config:
      --reference  Run TypeDoc command API reference build (Markdown)
                                                       [boolean] [default: true]
      --site       Run MkDocs build (HTML)             [boolean] [default: true]
  -d, --site-dir   HTML output directory   [string] [default: (from mkdocs.yml)]
      --title      Title of the API reference
                                    [string] [default: (extension package name)]
      --all        Output all reference docs (not just Appium comands) [boolean]

Custom Paths:
      --package-json   Path to package.json   [string] [default: ./package.json]
      --tsconfig-json  Path to tsconfig.json [string] [default: ./tsconfig.json]
      --mkdocs-yml     Path to mkdocs.yml       [string] [default: ./mkdocs.yml]
      --typedoc-json   Path to typedoc.json   [string] [default: ./typedoc.json]

Deployment Config:
      --deploy          Commit HTML output to a branch using mike      [boolean]
      --push            Push after deploy                              [boolean]
  -b, --branch          Branch to commit to         [string] [default: gh-pages]
  -r, --remote          Remote to push to             [string] [default: origin]
      --prefix          Subdirectory within <branch> to commit to       [string]
  -m, --message         Commit message. Use "%s" for version placeholder[string]
      --deploy-version  Version (directory) to deploy build to
                                 [string] [default: (derived from package.json)]
      --alias           Alias for the build (e.g., "latest"); triggers alias
                        update                        [string] [default: latest]
      --rebase          Rebase <branch> with remote before deploy      [boolean]

Dev Server Config:
      --serve  Start development server                                [boolean]
  -p, --port   Development server port                  [number] [default: 8000]
  -h, --host   Development server host             [string] [default: localhost]

Options:
      --help       Show help                                           [boolean]
      --version    Show version number                                 [boolean]
      --verbose    Alias for --log-level=debug                         [boolean]
  -L, --log-level  Sets the log level
         [choices: "debug", "info", "warn", "error", "silent"] [default: "info"]
  -c, --config     Path to config file
                                  [string] [default: (discovered automatically)]
      --no-config  Disable config file discovery                       [boolean]

For help with further configuration, see:
  - MkDocs: https://www.mkdocs.org
  - TypeDoc: https://typedoc.org
  - Mike: https://github.com/jimporter/mike

 ERROR                                                                                                                                                                                                                                                                                                 docutils:cli 11:19:38

Missing dependent arguments:
 rebase -> remote
```

**Comment by boneskull** [comment]
@jlipps that's... something's not right.  I can't reproduce that.

**Comment by boneskull** [comment]
@jlipps another way to test would be to do smth like this (from `appium-xcuitest-driver`)

```bash
../appium/node_modules/.bin/appium-docs --deploy -b docs-site -m 'docs: auto-build docs for appium-xcuitest-driver@%s'
```

`--rebase` should not be required.

**Comment by jlipps** [comment]
OK, when I removed `--rebase` from `publish:docs`, it got past that error. Now I'm running into another one:

````
> /opt/homebrew/bin/python3 -m mike deploy --config-file /Users/jlipps/Code/gh/appium/appium-xcuitest-driver/mkdocs.yml --remote origin --branch docs-site --message 'docs: auto-build docs for appium-xcuitest-driver@4.31.0' --rebase 4.31.0
/opt/homebrew/opt/python@3.11/bin/python3.11: No module named mike.__main__; 'mike' is a package and cannot be directly executed
```

**Comment by boneskull** [comment]
yeah something is f'd.  i can't get `mike` to run properly on my system.  try again with my latest changeset?  

my problem is that `mike` is not in my `PATH` and I have no idea why the default behavior of pip is to put executable scripts in a directory that is not in my `PATH`.  like REALLY?

**Comment by boneskull** [comment]
(so I was trying to correct for that, because if it's happening to _me_, it'll happen to somebody else)

note to self: try executing `mike` with a manual `PATH` in the `env` option containing `~/.local/bin`

**Comment by jlipps** [comment]
@boneskull ok this works now!

**Review by jlipps — APPROVED** [review]

**Comment by jlipps** [comment]
@boneskull we still have a problem though. we need mike's docs version to be `${major}.${minor}` not `${major}.${minor}.${patch}`. i.e., if we publish docs for a patch version, it should overwrite the current major/minor pair, not create a new directory.

**Pull request merged**
