### PR TITLE
Update Session C# samples

### PR DESCRIPTION
**Pull request by jova**
## Proposed changes

C# samples for session are done.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
@jova 
Thanks. Can you sign the CLA?
Please ensure signing email and email you commit to.

**Comment by jova** [comment]
i signed.

**Comment by KazuCocoa** [comment]
@jova thanks! but the CLA is pending...
Is the first commit remaining no-sign status?

**Comment by dpgraham** [comment]
Looks like you used two different accounts. Are you able to rebase it so that the first commit uses your main account?

**Comment by dpgraham** [comment]
@jova Are you able to rebase it so that commit 60de8b439db38f9cc03f34c31fb3e78646f22b34 is attached to your `jova` account instead of `Ersoy TORAMAN`

That, or you could sign the CLA as `Ersoy TORAMAN`.

I'd love to merge these in, but I can't move forward without this being resolved.

Thanks again for your contribution!

**Comment by jova** [comment]
@dpgraham Sorry, im newbie on git.

I rebased but im not sure for done. Can you check it? https://github.com/jova/appium

**Comment by dpgraham** [comment]
@jova I can help out with this later today. I still see the commit in there.

**Comment by dpgraham** [comment]
Try doing this:

```
git rebase -i HEAD~12
```

For commit `C# samples for session are done` replace the word `pick` with `squash`.

Then do a force push

```
git push origin +master
```

Let me know if that works for you.

**Comment by jova** [comment]
http://prntscr.com/lljs62

i already rebased and pushed. I try re-push. Is it still same?

**Review by dpgraham — APPROVED** [review]

**Comment by dpgraham** [comment]
Good now

**Pull request merged**
