### PR TITLE
doc/cn[2.0]: add "migrate doc" 、"driver-cli doc" and modify toc.js

### PR DESCRIPTION
**Pull request by youngfreeFJS**
## Proposed changes

doc/cn[2.0]: add "migrate doc" 、"driver-cli doc" and modify toc.js

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by youngfreeFJS** [comment]
hi, @jlipps @boneskull @mykola-mokhnach  @KazuCocoa 

This is the migrating to appium2.0 document of the CN version.

**Comment by youngfreeFJS** [comment]
Is `fossa-scan` a new check item? Should I need to configure anything？


> 
> `Running `fossa analyze` performs a dependency analysis and uploads the result
> to FOSSA. To run an analysis without uploading results, run:
> 
>     fossa analyze --output
> 
> You can provide your API key by setting the $FOSSA_API_KEY environment
> variable. For example, try running:
> 
>     FOSSA_API_KEY=<YOUR_API_KEY_HERE> $command
> 
> You can create an API key for your FOSSA account at:
>     
>     app.fossa.com/account/settings/integrations/api_tokens
> 
> 
> Error: Process completed with exit code 1.`

**Review by jlipps — APPROVED** [review]
amazing contribution, thanks @youngfreeFJS!

**Comment by boneskull** [comment]
yeah, no secrets in PRs. we should disable the scan for PR and run on push only

**Pull request merged**
