### PR TITLE
chore: update FOSSA workflow

### PR DESCRIPTION
**Pull request by boneskull**
This PR moves the FOSSA check from the Node workflow to its own.

Due to https://github.com/fossas/spectrometer/issues/346 this will now be a nightly check, and will _fail_ if there are unaddressed license issues (whereas before it would ignore them).  It will likely fail the first time it runs, and we'll need to go into the FOSSA app and manually set the issues to be ignored since they seem to only occur in multi-license repos or sample code.

It will check the `2.0` branch nightly.

### CODE REVIEW

**Comment by boneskull** [comment]
Note that the path check isn't happening yet, so I can test.

**Comment by boneskull** [comment]
either FOSSA is hosed or I have hosed something. hosing all around.  marking as draft until I can resolve this with FOSSA

**Comment by boneskull** [comment]
(see updated description)

**Review by KazuCocoa — APPROVED** [review]

**Comment by boneskull** [comment]
upstream issue is now https://github.com/fossas/fossa-cli/issues/694

**Review by jlipps — APPROVED** [review]

**Comment by boneskull** [comment]
Actually... I think I'll just merge this and see what happens.  That's really the only way to test a scheduled action anyhow...

**Pull request merged**
