### PR TITLE
chore(appium): refactor some variable/parameter names for clarity

### PR DESCRIPTION
**Pull request by boneskull**
renamed parameters named `ext` to `installSpec`, since these correspond to the values of `installSpec` in the manifest

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* 2.0
  * **PR #16887** <a href="https://app.graphite.dev/github/pr/appium/appium/16887" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium/16887?utm_source=stack-comment).

**Comment by boneskull** [comment]
mainly trying to reduce confusion about what kind of "name" we are dealing with.  `installSpec` is not `extName`, for example (though this could also be more clear), but `ext` doesn't tell me enough

**Review by jlipps — APPROVED** [review]
was hard to tell what was an actual change and what was what appears to be prettier reformatting. so i'll trust you that the rename is safe.

**Comment by boneskull** [comment]
this also adds `installSpec` as a parameter to `validateExtensionFields` so that the subclasses can display more relevant information about which extension actually had a problem

**Pull request merged**
