### PR TITLE
Adding support for chrome browser rotation

### PR DESCRIPTION
**Pull request by yaphatak**
Adding support for chrome browser rotation

### CODE REVIEW

**Comment by yaphatak** [comment]
I reverted first commit by mistake both are same commits. @jlipps : can you have look?

**Comment by moizjv** [comment]
@yaphatak you would need to squash in one commit

**Comment by yaphatak** [comment]
@moizjv I accidentally reverted first commit. Its same change just one file change. Is this not enough or should i send new PR?

**Comment by imurchie** [comment]
"Squashing" will allow you to bring them into a single commit. See [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).

**Comment by yaphatak** [comment]
@imurchie : I tried to squash it but i ended up adding seb changes to my commit. Let me send separate PR with new repositry. I am not used to GITHUB, sorry about that.I am closing this one for now.

**Pull request closed without merging**
