### PR TITLE
Doc Tweaks

### LINKED ISSUE #6252: Document - update Mobile JSON Wire Protocol link
## The problem
#6248 fixes the JSON Wire Protocol link, but the `Mobile JSON Wire Protocol` links are still pointing to the decommissioned code.google.com URL.

## Details

The current documents like
* https://github.com/appium/appium/blob/master/docs/en/about-appium/intro.md 
* https://github.com/appium/appium/blob/master/docs/en/about-appium/appium-clients.md 

are still pointing to `https://code.google.com/p/selenium/source/browse/spec-draft.md?repo=mobile` for Mobile JSON Wire Protocol reference, which is resolved to a deprecated link now.

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
## Proposed changes

Fixes #6252 
## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by imurchie** [comment]
LGTM.

**Comment by moizjv** [comment]
Can one of the admins verify this patch?

**Comment by SrinivasanTarget** [comment]
@imurchie On a different note.I didn't see our core repo in coveralls and may i know what does it do,
https://github.com/appium/appium/blob/master/.travis.yml#L8

**Comment by imurchie** [comment]
Coveralls? It reports how much of the codebase is covered by unit tests.

**Comment by SrinivasanTarget** [comment]
Yes but our core repo is not available in https://coveralls.io/github/appium. Does this trigger all the unit tests available in other modules and update in coveralls?

**Comment by SrinivasanTarget** [comment]
Apologies if this is a silly query.But i wonder what does this do when coveralls doesn't have this configured for core repo.

**Comment by imurchie** [comment]
No, each repo is on its own. There is no carry over.

**Comment by imurchie** [comment]
I just turned it on, for the fun of it.

**Comment by SrinivasanTarget** [comment]
:+1:

**Pull request merged**
