### PR TITLE
fix(base-driver): Make sure we never mutate incoming args

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Review by boneskull — APPROVED** [review]
This seems fine to me, but I'm curious:

1. Why do we mutate the value?
2. What bug does this cause?

**Comment by mykola-mokhnach** [comment]
> This seems fine to me, but I'm curious:
> 
> 1. Why do we mutate the value?

We should not. This is what the fix does

> 2. What bug does this cause?

It should not be a real deal when Appium is running as http-server, but internal tests are failing nevertheless:

https://github.com/appium/appium-android-driver/pull/735
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=20424&view=logs&j=d4d48b56-56f2-5159-6052-c4831402bb90&t=89e5db65-2b81-5ecf-de1e-097733dadfbd

**Comment by mykola-mokhnach** [comment]
Thanks for the review @boneskull 
I'm still not quite sure what to do with `core.js` file, which is a duplicate of what exists in `driver.js`. Which of them is a true one?

**Comment by boneskull** [comment]
@mykola-mokhnach `core.js` and `driver.js` are different.  you might want to try to merge again...

`core.js` contains `DriverCore` which is now the base class for `BaseDriver` (initially class `BaseDriverCore`) and `AppiumDriver`.  `BaseDriverCore` contains stuff that either a) `AppiumDriver` doesn't need or b) conflicts with `AppiumDriver`.

**Comment by boneskull** [comment]
@mykola-mokhnach 

> Why do we mutate the value?
> > We should not. This is what the fix does

Errr, yes, but rather I mean: why was this happening in the first place?  Where exactly is the object mutated, and why?

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach
> 
> > Why do we mutate the value?
> > > We should not. This is what the fix does
> 
> Errr, yes, but rather I mean: why was this happening in the first place? Where exactly is the object mutated, and why?

It looks like its mutated in one of helper methods that strip out capability prefixes inside of createSession

**Pull request merged**
